﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace MonitoringSuiteLibrary
{
    public partial class DistressDetect
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"Gender", @"Gender", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Age", @"Age"),new InputOutputColumnPair(@"BloodOxy", @"BloodOxy"),new InputOutputColumnPair(@"HeartRate", @"HeartRate"),new InputOutputColumnPair(@"Systolic Blood Pressure", @"Systolic Blood Pressure"),new InputOutputColumnPair(@"Diastolic Blood Pressure", @"Diastolic Blood Pressure"),new InputOutputColumnPair(@"Respiratory Rate", @"Respiratory Rate"),new InputOutputColumnPair(@"Temperature", @"Temperature")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Gender",@"Age",@"BloodOxy",@"HeartRate",@"Systolic Blood Pressure",@"Diastolic Blood Pressure",@"Respiratory Rate",@"Temperature"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression(new LbfgsLogisticRegressionBinaryTrainer.Options(){L1Regularization=0.05449092F,L2Regularization=0.3433804F,LabelColumnName=@"Distress",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
