
// This file was auto-generated by ML.NET Model Builder. 

using ML_Model;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Gender = @"M",
    Age = 58F,
    BloodOxy = 94F,
    HeartRate = 169F,
    Systolic_Blood_Pressure = 130F,
    Diastolic_Blood_Pressure = 86F,
    Respiratory_Rate = 9F,
    Temperature = 102.08F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Distress with predicted Distress from sample data...\n\n");


Console.WriteLine($"Gender: {@"M"}");
Console.WriteLine($"Age: {58F}");
Console.WriteLine($"BloodOxy: {94F}");
Console.WriteLine($"HeartRate: {180F}");
Console.WriteLine($"Systolic_Blood_Pressure: {140F}");
Console.WriteLine($"Diastolic_Blood_Pressure: {85F}");
Console.WriteLine($"Respiratory_Rate: {8F}");
Console.WriteLine($"Temperature: {102.48F}");


Console.WriteLine($"\n\nPredicted Distress: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

