CI-FirstResponders: DispatchersMonitoringTool.Services.ThemeSelectorService Class Reference
DispatchersMonitoringTool.Services.ThemeSelectorService Class Reference
Public Member Functions
ThemeSelectorService ()
void InitializeTheme ()
void SetTheme (AppTheme theme)
AppTheme GetCurrentTheme ()
void InitializeTheme ()
void SetTheme (AppTheme theme)
AppTheme GetCurrentTheme ()
Constructor & Destructor Documentation
ThemeSelectorService()
DispatchersMonitoringTool.Services.ThemeSelectorService.ThemeSelectorService ()
Member Function Documentation
GetCurrentTheme()
AppTheme DispatchersMonitoringTool.Services.ThemeSelectorService.GetCurrentTheme ()
Implements DispatchersMonitoringTool.Contracts.Services.IThemeSelectorService.
Referenced by DispatchersMonitoringTool.Services.ThemeSelectorService.InitializeTheme().
InitializeTheme()
void DispatchersMonitoringTool.Services.ThemeSelectorService.InitializeTheme ()
Implements DispatchersMonitoringTool.Contracts.Services.IThemeSelectorService.
References DispatchersMonitoringTool.Services.ThemeSelectorService.GetCurrentTheme(), and DispatchersMonitoringTool.Services.ThemeSelectorService.SetTheme().
SetTheme()
void DispatchersMonitoringTool.Services.ThemeSelectorService.SetTheme (AppTheme theme)
Implements DispatchersMonitoringTool.Contracts.Services.IThemeSelectorService.
Referenced by DispatchersMonitoringTool.Services.ThemeSelectorService.InitializeTheme().
The documentation for this class was generated from the following file:
DispatchersMonitoringTool/DispatchersMonitoringTool/Services/ThemeSelectorService.cs