CI-FirstResponders: DistressDetector.DistressDetect Class Reference
DistressDetector.DistressDetect Class Reference
Classes
class ModelInput
model input class for DistressDetect.
class ModelOutput
model output class for DistressDetect.
Static Public Member Functions
static ModelOutput Predict (ModelInput input)
Use this method to predict on ModelInput.
static ITransformer RetrainPipeline (MLContext mlContext, IDataView trainData)
Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
static IEstimator< ITransformer > BuildPipeline (MLContext mlContext)
build the pipeline that is used from model builder. Use this function to retrain model.
Static Public Attributes
static readonly Lazy< PredictionEngine< ModelInput, ModelOutput > > PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true)
Member Function Documentation
BuildPipeline()
static IEstimator< ITransformer > DistressDetector.DistressDetect.BuildPipeline (MLContext mlContext) static
build the pipeline that is used from model builder. Use this function to retrain model.
Parameters
mlContext
Returns
Referenced by DistressDetector.DistressDetect.RetrainPipeline().
Predict()
static ModelOutput DistressDetector.DistressDetect.Predict (ModelInput input) static
Use this method to predict on ModelInput.
Parameters
input model input.
Returns
See also
ModelOutput
References DistressDetector.DistressDetect.PredictEngine.
Referenced by DistressDetector.Status.DistressStatus().
RetrainPipeline()
static ITransformer DistressDetector.DistressDetect.RetrainPipeline (MLContext mlContext, IDataView trainData) static
Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
Parameters
mlContext
trainData
Returns
References DistressDetector.DistressDetect.BuildPipeline().
Member Data Documentation
PredictEngine
readonly Lazy<PredictionEngine<ModelInput, ModelOutput> > DistressDetector.DistressDetect.PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true) static
Referenced by DistressDetector.DistressDetect.Predict().
The documentation for this class was generated from the following files:
DistressML/DistressDetector/DistressDetect.consumption.cs
DistressML/DistressDetector/DistressDetect.training.cs