CI-FirstResponders: MonitoringSuiteLibrary.MachineLearning.CheckDistressONNX Class Reference
MonitoringSuiteLibrary.MachineLearning.CheckDistressONNX Class Reference
The new class that uses the python ONNX machine learning implementation to check the distress status of first responders. This references the DistressONNXModel.onnx file as it's source for the machine learning model.
Static Public Member Functions
static bool GetDistressStatus (int age, char sex, Vitals v, string path)
Check the distress status of a First Responder object using it's age, gender, and vitals data.
Detailed Description
The new class that uses the python ONNX machine learning implementation to check the distress status of first responders. This references the DistressONNXModel.onnx file as it's source for the machine learning model.
Member Function Documentation
GetDistressStatus()
static bool MonitoringSuiteLibrary.MachineLearning.CheckDistressONNX.GetDistressStatus (int age, char sex, Vitals v, string path) static
Check the distress status of a First Responder object using it's age, gender, and vitals data.
Parameters
age The first responders age id.
sex The first responders gender.
v The first responders Vitals data.
path The path to the ONNX file containing the machine learning implementation..
Returns
Returns a boolean representing the distress status of a first responder.
References MonitoringSuiteLibrary.Models.Vitals.BloodOxy, MonitoringSuiteLibrary.Models.Vitals.DiaBP, MonitoringSuiteLibrary.Models.Vitals.HeartRate, MonitoringSuiteLibrary.Models.Vitals.RespRate, and MonitoringSuiteLibrary.Models.Vitals.SysBP.
Referenced by MobileVitalsMonitoringTool.ViewModels.AboutViewModel.AboutViewModel(), UnitTests.MLTests.TestInDistress(), and UnitTests.MLTests.TestNotDistress().
The documentation for this class was generated from the following file:
MonitoringSuiteLibrary/MonitoringSuiteLibrary/MachineLearning/CheckDistressONNX.cs