CI-FirstResponders: MonitoringSuiteLibrary.Services.DataService Class Reference
MonitoringSuiteLibrary.Services.DataService Class Reference
Concrete implementation of the first responder data service.
Public Member Functions
DataService (IOptions< DataServiceConfiguration > options)
Creates a DataService.
async Task< IEnumerable< FirstResponder > > GetActiveFirstRespondersAsync ()
Asynchronous function that queries the database to retrieve all active first responder's information from the workers table along with their corresponding vitals and location.
async Task< FirstResponder?> GetFirstResponderAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve a first responder's information from the workers table along with their corresponding vitals and location.
async Task< IEnumerable< FirstResponder > > GetFirstRespondersAsync (int eventId)
Asynchronous function that queries the database to retrieve all first responder's information from the workers table that responded to a particular event along with their corresponding vitals and location.
async Task< Vitals?> GetFirstResponderVitalsAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve the vitals entry of a first responder.
async Task< Location?> GetFirstResponderLocationAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve the location entry of a first responder.
async Task< bool > SetFirstResponderInactiveAsync (int firstResponderId)
Modifies a first responder's active status to false.
async Task< bool > SetFirstResponderActiveAsync (int firstResponderId)
Modifies a first responder's active status to true.
async Task< bool > SetFirstResponderAlertFalseAsync (int firstResponderId)
Sets a first responder alert status as false.
async Task< bool > SetFirstResponderAlertTrueAsync (int firstResponderId)
Sets a first responder alert status as true.
async Task< bool > DeleteFirstResponderVitalsAsync (int firstResponderId)
Deletes a first responder vitals. This is done when a first responder is changed to inactive.
async Task< bool > DeleteFirstResponderLocationAsync (int firstResponderId)
Deletes a first responder location. This is done when a first responder is changed to inactive.
async Task< bool > CreateFirstResponderLocationAsync (int firstResponderId, Location location)
Creates a location entry of a first responder.
async Task< bool > CreateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Creates a vitals entry for a first responder.
async Task< bool > UpdateFirstResponderLocationAsync (int firstResponderId, Location location)
Updates the location of a first responder.
async Task< bool > UpdateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Updates the vitals of a first responder.
async Task< bool > FirstResponderExistsAsync (int firstResponderId)
Checks if first responder exists in the database based on worker ID.
async Task< bool > FirstResponderIsActiveAsync (int firstResponderId)
Checks if first responder is active.
async Task< bool > FirstResponderHasAlertAsync (int firstResponderId)
Checks if first responder has an active alert.
Task< IEnumerable< FirstResponder > > GetActiveFirstRespondersAsync ()
Gets a IEnumerable<FirstResponder> representing the active first responders.
Task< FirstResponder?> GetFirstResponderAsync (int firstResponderId)
Gets a FirstResponder.
Task< IEnumerable< FirstResponder > > GetFirstRespondersAsync (int eventId)
Gets a IEnumerable<FirstResponder> respresenting the first responders for an event.
Task< Vitals?> GetFirstResponderVitalsAsync (int firstResponderId)
Gets a FirstResponders vitals.
Task< Location?> GetFirstResponderLocationAsync (int firstResponderId)
Gets a FirstResponders location.
Task< bool > SetFirstResponderInactiveAsync (int firstResponderId)
Sets a first responder as inactive.
Task< bool > SetFirstResponderActiveAsync (int firstResponderId)
Sets a first responder as active.
Task< bool > SetFirstResponderAlertFalseAsync (int firstResponderId)
Sets a first responder alert status as false.
Task< bool > SetFirstResponderAlertTrueAsync (int firstResponderId)
Sets a first responder alert status as true.
Task< bool > DeleteFirstResponderVitalsAsync (int firstResponderId)
Deletes a first responder vitals. This is done when a first responder is changed to inactive.
Task< bool > DeleteFirstResponderLocationAsync (int firstResponderId)
Deletes a first responder location. This is done when a first responder is changed to inactive.
Task< bool > CreateFirstResponderLocationAsync (int firstResponderId, Location location)
Creates a location entry of a first responder.
Task< bool > CreateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Creates a vitals entry for a first responder.
Task< bool > UpdateFirstResponderLocationAsync (int firstResponderId, Location location)
Updates the location of a first responder.
Task< bool > UpdateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Updates the vitals of a first responder.
Task< bool > FirstResponderExistsAsync (int firstResponderId)
Checks if first responder exists in the database based on worker ID.
Task< bool > FirstResponderIsActiveAsync (int firstResponderId)
Checks if first responder is active.
Task< bool > FirstResponderHasAlertAsync (int firstResponderId)
Checks if first responder has an active alert.
Detailed Description
Concrete implementation of the first responder data service.
Constructor & Destructor Documentation
DataService()
MonitoringSuiteLibrary.Services.DataService.DataService (IOptions< DataServiceConfiguration > options)
Creates a DataService.
Parameters
options The IOptions of type DataServiceConfiguration to use.
Member Function Documentation
CreateFirstResponderLocationAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.CreateFirstResponderLocationAsync (int firstResponderId, Location location)
Creates a location entry of a first responder.
Parameters
firstResponderId The id of the first responder corresponding to the created location.
location A Location object.
Returns
Whether or not the update was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Models.Location.XCoord, MonitoringSuiteLibrary.Models.Location.YCoord, and MonitoringSuiteLibrary.Models.Location.ZCoord.
CreateFirstResponderVitalsAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.CreateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Creates a vitals entry for a first responder.
Parameters
firstResponderId The id of the first responder corresponding to the created vitals.
vitals A Vitals object.
Returns
Whether or not the update was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Models.Vitals.BloodOxy, MonitoringSuiteLibrary.Models.Vitals.DiaBP, MonitoringSuiteLibrary.Models.Vitals.HeartRate, MonitoringSuiteLibrary.Models.Vitals.RespRate, MonitoringSuiteLibrary.Models.Vitals.SysBP, and MonitoringSuiteLibrary.Models.Vitals.TempF.
DeleteFirstResponderLocationAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.DeleteFirstResponderLocationAsync (int firstResponderId)
Deletes a first responder location. This is done when a first responder is changed to inactive.
Parameters
firstResponderId The id of the target first responder.
Returns
Whether or not setting the first responder as inactive was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
DeleteFirstResponderVitalsAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.DeleteFirstResponderVitalsAsync (int firstResponderId)
Deletes a first responder vitals. This is done when a first responder is changed to inactive.
Parameters
firstResponderId The id of the target first responder.
Returns
Whether or not setting the first responder as inactive was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
FirstResponderExistsAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.FirstResponderExistsAsync (int firstResponderId)
Checks if first responder exists in the database based on worker ID.
Parameters
firstResponderId The id of the first responder to check.
Returns
Whether or not the worker id exists in the worker table in the database.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
FirstResponderHasAlertAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.FirstResponderHasAlertAsync (int firstResponderId)
Checks if first responder has an active alert.
Parameters
firstResponderId The id of the first responder to check.
Returns
Whether or not the worker's alert field is true in the database.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
FirstResponderIsActiveAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.FirstResponderIsActiveAsync (int firstResponderId)
Checks if first responder is active.
Parameters
firstResponderId The id of the first responder to check.
Returns
Whether or not the worker's active field is true in the database.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
GetActiveFirstRespondersAsync()
async Task< IEnumerable< FirstResponder > > MonitoringSuiteLibrary.Services.DataService.GetActiveFirstRespondersAsync ()
Asynchronous function that queries the database to retrieve all active first responder's information from the workers table along with their corresponding vitals and location.
Returns
A collection of FirstResponder objects.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderLocationAsync(), and MonitoringSuiteLibrary.Services.DataService.GetFirstResponderVitalsAsync().
GetFirstResponderAsync()
async Task< FirstResponder?> MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve a first responder's information from the workers table along with their corresponding vitals and location.
Parameters
firstResponderId The unique id of the first responder.
Returns
The FirstResponder corresponding to the firstResponderId .
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderLocationAsync(), and MonitoringSuiteLibrary.Services.DataService.GetFirstResponderVitalsAsync().
Referenced by MonitoringSuiteLibrary.Services.DataService.FirstResponderExistsAsync(), MonitoringSuiteLibrary.Services.DataService.FirstResponderHasAlertAsync(), MonitoringSuiteLibrary.Services.DataService.FirstResponderIsActiveAsync(), and MonitoringSuiteLibrary.Services.DataService.GetFirstRespondersAsync().
GetFirstResponderLocationAsync()
async Task< Location?> MonitoringSuiteLibrary.Services.DataService.GetFirstResponderLocationAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve the location entry of a first responder.
Parameters
firstResponderId The unique id of the first responder.
Returns
The Location corresponding to the firstResponderId .
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
Referenced by MonitoringSuiteLibrary.Services.DataService.GetActiveFirstRespondersAsync(), and MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
GetFirstRespondersAsync()
async Task< IEnumerable< FirstResponder > > MonitoringSuiteLibrary.Services.DataService.GetFirstRespondersAsync (int eventId)
Asynchronous function that queries the database to retrieve all first responder's information from the workers table that responded to a particular event along with their corresponding vitals and location.
Parameters
eventId The id of the event corresponding to the target first responders.
Returns
A collection of FirstResponder objects.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
GetFirstResponderVitalsAsync()
async Task< Vitals?> MonitoringSuiteLibrary.Services.DataService.GetFirstResponderVitalsAsync (int firstResponderId)
Asynchronous function that queries the database to retrieve the vitals entry of a first responder.
Parameters
firstResponderId The unique id of the first responder.
Returns
The Vitals corresponding to the firstResponderId .
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
Referenced by MonitoringSuiteLibrary.Services.DataService.GetActiveFirstRespondersAsync(), and MonitoringSuiteLibrary.Services.DataService.GetFirstResponderAsync().
SetFirstResponderActiveAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.SetFirstResponderActiveAsync (int firstResponderId)
Modifies a first responder's active status to true.
Parameters
firstResponderId The id corresponding to the first responder to modify.
Returns
Whether or not setting the first responder as inactive was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
SetFirstResponderAlertFalseAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.SetFirstResponderAlertFalseAsync (int firstResponderId)
Sets a first responder alert status as false.
Parameters
firstResponderId The id of the target first responder.
Returns
Whether or not setting the first responder's alert to false was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
SetFirstResponderAlertTrueAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.SetFirstResponderAlertTrueAsync (int firstResponderId)
Sets a first responder alert status as true.
Parameters
firstResponderId The id of the target first responder.
Returns
Whether or not setting the first responder's alert to true was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
SetFirstResponderInactiveAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.SetFirstResponderInactiveAsync (int firstResponderId)
Modifies a first responder's active status to false.
Parameters
firstResponderId The id corresponding to the first responder to modify.
Returns
Whether or not setting the first responder as inactive was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
UpdateFirstResponderLocationAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.UpdateFirstResponderLocationAsync (int firstResponderId, Location location)
Updates the location of a first responder.
Parameters
firstResponderId The id of the first responder to update.
location A Location object.
Returns
Whether or not the update was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Models.Location.XCoord, MonitoringSuiteLibrary.Models.Location.YCoord, and MonitoringSuiteLibrary.Models.Location.ZCoord.
UpdateFirstResponderVitalsAsync()
async Task< bool > MonitoringSuiteLibrary.Services.DataService.UpdateFirstResponderVitalsAsync (int firstResponderId, Vitals vitals)
Updates the vitals of a first responder.
Parameters
firstResponderId The id of the first responder to update.
vitals A Vitals object.
Returns
Whether or not the update was successful.
Implements MonitoringSuiteLibrary.Contracts.Services.IDataService.
References MonitoringSuiteLibrary.Models.Vitals.BloodOxy, MonitoringSuiteLibrary.Models.Vitals.DiaBP, MonitoringSuiteLibrary.Models.Vitals.HeartRate, MonitoringSuiteLibrary.Models.Vitals.RespRate, MonitoringSuiteLibrary.Models.Vitals.SysBP, and MonitoringSuiteLibrary.Models.Vitals.TempF.
The documentation for this class was generated from the following file:
MonitoringSuiteLibrary/MonitoringSuiteLibrary/Services/DataService.cs