CI-FirstResponders: DispatchersMonitoringTool.App Class Reference
DispatchersMonitoringTool.App Class Reference
App.
Public Member Functions
T GetService< T > ()
App ()
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
void InitializeComponent ()
InitializeComponent.
Static Public Member Functions
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
Detailed Description
App.
Constructor & Destructor Documentation
App()
DispatchersMonitoringTool.App.App ()
Member Function Documentation
GetService< T >()
T DispatchersMonitoringTool.App.GetService< T > ()
Type Constraints
T : class
T : _host.Services.GetService
T : typeof
T : T
T : as
T : T
InitializeComponent() [1/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
Referenced by DispatchersMonitoringTool.App.Main().
InitializeComponent() [2/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
InitializeComponent() [3/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
InitializeComponent() [4/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
InitializeComponent() [5/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
InitializeComponent() [6/6]
void DispatchersMonitoringTool.App.InitializeComponent ()
InitializeComponent.
Main() [1/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
Main() [2/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
Main() [3/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
Main() [4/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
Main() [5/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
Main() [6/6]
static void DispatchersMonitoringTool.App.Main () static
Application Entry Point.
References DispatchersMonitoringTool.App.InitializeComponent().
The documentation for this class was generated from the following files:
DispatchersMonitoringTool/DispatchersMonitoringTool/App.xaml.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net6.0-windows/App.g.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net6.0-windows/App.g.i.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net6.0-windows10.0.19041.0/App.g.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net6.0-windows10.0.19041.0/App.g.i.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net7.0-windows/App.g.cs
DispatchersMonitoringTool/DispatchersMonitoringTool/obj/Debug/net7.0-windows/App.g.i.cs