CI-FirstResponders: Ort Namespace Reference
Ort Namespace Reference
All C++ Onnxruntime APIs are defined inside this namespace.
Namespaces
namespace detail
Classes
struct Allocator
Wrapper around OrtAllocator.
struct AllocatorWithDefaultOptions
Wrapper around OrtAllocator default instance that is owned by Onnxruntime.
struct ArenaCfg
it is a structure that represents the configuration of an arena based allocator
struct BFloat16_t
bfloat16 (Brain Floating Point) data type
struct CustomOpApi
This entire structure is deprecated, but we not marking it as a whole yet since we want to preserve for the next release.
struct CustomOpBase
struct CustomOpConfigs
Class that represents session configuration entries for one or more custom operators.
struct CustomOpDomain
Custom Op Domain.
struct Env
The Env (Environment)
struct Exception
All C++ methods that can fail will throw an exception of this type.
struct Float16_t
IEEE 754 half-precision floating point data type.
struct Global
struct IoBinding
Wrapper around ::OrtIoBinding.
struct KernelContext
This class wraps a raw pointer OrtKernelContext* that is being passed to the custom kernel Compute() method. Use it to safely access context attributes, input and output parameters with exception safety guarantees. See usage example in onnxruntime/test/testdata/custom_op_library/custom_op_library.cc.
struct KernelInfo
This struct owns the OrtKernInfo* pointer when a copy is made. For convenient wrapping of OrtKernelInfo* passed to kernel constructor and query attributes, warp the pointer with Ort::Unowned<KernelInfo> instance so it does not destroy the pointer the kernel does not own.
struct MapTypeInfo
Wrapper around ::OrtMapTypeInfo.
struct MemoryAllocation
Represents native memory allocation coming from one of the OrtAllocators registered with OnnxRuntime. Use it to wrap an allocation made by an allocator so it can be automatically released when no longer needed.
struct MemoryInfo
Wrapper around ::OrtMemoryInfo.
struct ModelMetadata
Wrapper around ::OrtModelMetadata.
struct Op
Create and own custom defined operation.
struct OpAttr
This struct provides life time management for custom op attribute.
struct RunOptions
RunOptions.
struct SequenceTypeInfo
Wrapper around ::OrtSequenceTypeInfo.
struct Session
Wrapper around ::OrtSession.
struct SessionOptions
Wrapper around ::OrtSessionOptions.
struct Status
The Status that holds ownership of OrtStatus received from C API Use it to safely destroy OrtStatus* returned from the C API. Use appropriate constructors to construct an instance of a Status object from exceptions.
struct TensorTypeAndShapeInfo
Wrapper around ::OrtTensorTypeAndShapeInfo.
struct ThreadingOptions
The ThreadingOptions.
struct TypeInfo
Type information that may contain either TensorTypeAndShapeInfo or the information about contained sequence or map depending on the ONNXType.
struct TypeToTensorType
struct TypeToTensorType< BFloat16_t >
struct TypeToTensorType< bool >
struct TypeToTensorType< double >
struct TypeToTensorType< float >
struct TypeToTensorType< Float16_t >
struct TypeToTensorType< int16_t >
struct TypeToTensorType< int32_t >
struct TypeToTensorType< int64_t >
struct TypeToTensorType< int8_t >
struct TypeToTensorType< uint16_t >
struct TypeToTensorType< uint32_t >
struct TypeToTensorType< uint64_t >
struct TypeToTensorType< uint8_t >
struct Value
Wrapper around ::OrtValue.
Typedefs
using AllocatedStringPtr = std::unique_ptr< char, detail::AllocatedFree >
unique_ptr typedef used to own strings allocated by OrtAllocators and release them at the end of the scope. The lifespan of the given allocator must eclipse the lifespan of AllocatedStringPtr instance
using UnownedSessionOptions = detail::SessionOptionsImpl< detail::Unowned< OrtSessionOptions > >
using ConstSessionOptions = detail::ConstSessionOptionsImpl< detail::Unowned< const OrtSessionOptions > >
using ConstSession = detail::ConstSessionImpl< detail::Unowned< const OrtSession > >
using UnownedSession = detail::SessionImpl< detail::Unowned< OrtSession > >
using ConstMemoryInfo = detail::MemoryInfoImpl< detail::Unowned< const OrtMemoryInfo > >
using ConstTensorTypeAndShapeInfo = detail::TensorTypeAndShapeInfoImpl< detail::Unowned< const OrtTensorTypeAndShapeInfo > >
using ConstSequenceTypeInfo = detail::SequenceTypeInfoImpl< detail::Unowned< const OrtSequenceTypeInfo > >
using ConstMapTypeInfo = detail::MapTypeInfoImpl< detail::Unowned< const OrtMapTypeInfo > >
using ConstTypeInfo = detail::TypeInfoImpl< detail::Unowned< const OrtTypeInfo > >
Contains a constant, unowned OrtTypeInfo that can be copied and passed around by value. Provides access to const OrtTypeInfo APIs.
using ConstValue = detail::ConstValueImpl< detail::Unowned< const OrtValue > >
using UnownedValue = detail::ValueImpl< detail::Unowned< OrtValue > >
using UnownedAllocator = detail::AllocatorImpl< detail::Unowned< OrtAllocator > >
using ConstIoBinding = detail::ConstIoBindingImpl< detail::Unowned< const OrtIoBinding > >
using UnownedIoBinding = detail::IoBindingImpl< detail::Unowned< OrtIoBinding > >
using ConstKernelInfo = detail::KernelInfoImpl< detail::Unowned< const OrtKernelInfo > >
Functions
const OrtApi & GetApi ()
This returns a reference to the OrtApi interface in use.
std::vector< std::string > GetAvailableProviders ()
This is a C++ wrapper for OrtApi::GetAvailableProviders() and returns a vector of strings representing the available execution providers.
void ThrowOnError (OrtStatus *ort_status)
void ThrowOnError (const Status &st)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
SessionOptions & AddInitializer (const char *name, const OrtValue *ort_val)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
std::string CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo *info, _In_ const char *name)
Detailed Description
All C++ Onnxruntime APIs are defined inside this namespace.
Typedef Documentation
AllocatedStringPtr
typedef std::unique_ptr< char, detail::AllocatedFree > Ort::AllocatedStringPtr
unique_ptr typedef used to own strings allocated by OrtAllocators and release them at the end of the scope. The lifespan of the given allocator must eclipse the lifespan of AllocatedStringPtr instance
ConstIoBinding
typedef detail::ConstIoBindingImpl< detail::Unowned< const OrtIoBinding > > Ort::ConstIoBinding
ConstKernelInfo
typedef detail::KernelInfoImpl< detail::Unowned< const OrtKernelInfo > > Ort::ConstKernelInfo
ConstMapTypeInfo
typedef detail::MapTypeInfoImpl< detail::Unowned< const OrtMapTypeInfo > > Ort::ConstMapTypeInfo
ConstMemoryInfo
typedef detail::MemoryInfoImpl< detail::Unowned< const OrtMemoryInfo > > Ort::ConstMemoryInfo
ConstSequenceTypeInfo
typedef detail::SequenceTypeInfoImpl< detail::Unowned< const OrtSequenceTypeInfo > > Ort::ConstSequenceTypeInfo
ConstSession
typedef detail::ConstSessionImpl< detail::Unowned< const OrtSession > > Ort::ConstSession
ConstSessionOptions
typedef detail::ConstSessionOptionsImpl< detail::Unowned< const OrtSessionOptions > > Ort::ConstSessionOptions
ConstTensorTypeAndShapeInfo
typedef detail::TensorTypeAndShapeInfoImpl< detail::Unowned< const OrtTensorTypeAndShapeInfo > > Ort::ConstTensorTypeAndShapeInfo
ConstTypeInfo
typedef detail::TypeInfoImpl< detail::Unowned< const OrtTypeInfo > > Ort::ConstTypeInfo
Contains a constant, unowned OrtTypeInfo that can be copied and passed around by value. Provides access to const OrtTypeInfo APIs.
ConstValue
typedef detail::ConstValueImpl< detail::Unowned< const OrtValue > > Ort::ConstValue
UnownedAllocator
typedef detail::AllocatorImpl< detail::Unowned< OrtAllocator > > Ort::UnownedAllocator
UnownedIoBinding
typedef detail::IoBindingImpl< detail::Unowned< OrtIoBinding > > Ort::UnownedIoBinding
UnownedSession
typedef detail::SessionImpl< detail::Unowned< OrtSession > > Ort::UnownedSession
UnownedSessionOptions
typedef detail::SessionOptionsImpl< detail::Unowned< OrtSessionOptions > > Ort::UnownedSessionOptions
UnownedValue
typedef detail::ValueImpl< detail::Unowned< OrtValue > > Ort::UnownedValue
Function Documentation
AddInitializer()
SessionOptions & Ort::AddInitializer (const char * name, const OrtValue * ort_val)
Referenced by Ort::detail::SessionOptionsImpl< T >::AddInitializer().
CustomOpApi::KernelInfoGetAttribute< std::string >() [1/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [2/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [3/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [4/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [5/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [6/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
CustomOpApi::KernelInfoGetAttribute< std::string >() [7/7]
template<> std::string Ort::CustomOpApi::KernelInfoGetAttribute< std::string > (_In_ const OrtKernelInfo * info, _In_ const char * name)
References ThrowOnError().
GetApi()
const OrtApi & Ort::GetApi ()
This returns a reference to the OrtApi interface in use.
Referenced by Ort::CustomOpDomain::Add(), Ort::detail::SessionOptionsImpl< T >::Add(), Ort::RunOptions::AddConfigEntry(), Ort::detail::SessionOptionsImpl< T >::AddConfigEntry(), Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers(), Ort::detail::SessionOptionsImpl< T >::AddInitializer(), Ort::detail::AllocatorImpl< T >::Alloc(), Ort::Allocator::Allocator(), Ort::AllocatorWithDefaultOptions::AllocatorWithDefaultOptions(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2(), Ort::detail::SessionOptionsImpl< OrtSessionOptions >::AppendExecutionProvider_MIGraphX(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2(), Ort::ArenaCfg::ArenaCfg(), Ort::detail::ValueImpl< T >::At(), Ort::detail::IoBindingImpl< T >::BindInput(), Ort::detail::IoBindingImpl< T >::BindOutput(), Ort::detail::IoBindingImpl< T >::ClearBoundInputs(), Ort::detail::IoBindingImpl< T >::ClearBoundOutputs(), Ort::detail::KernelInfoImpl< T >::Copy(), Ort::Op::Create(), Ort::Env::CreateAndRegisterAllocator(), Ort::MemoryInfo::CreateCpu(), Ort::Value::CreateMap(), Ort::Value::CreateOpaque(), Ort::Value::CreateSequence(), Ort::Value::CreateSparseTensor(), Ort::Value::CreateTensor(), Ort::CustomOpDomain::CustomOpDomain(), Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena(), Ort::detail::SessionOptionsImpl< T >::DisableMemPattern(), Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads(), Ort::detail::SessionOptionsImpl< T >::DisableProfiling(), Ort::Env::DisableTelemetryEvents(), Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena(), Ort::detail::SessionOptionsImpl< T >::EnableMemPattern(), Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps(), Ort::detail::SessionOptionsImpl< T >::EnableProfiling(), Ort::Env::EnableTelemetryEvents(), Ort::detail::SessionImpl< T >::EndProfilingAllocated(), Ort::Env::Env(), Ort::detail::ValueImpl< T >::FillSparseTensorBlockSparse(), Ort::detail::ValueImpl< T >::FillSparseTensorCoo(), Ort::detail::ValueImpl< T >::FillSparseTensorCsr(), Ort::detail::ValueImpl< T >::FillStringTensor(), Ort::detail::ValueImpl< T >::FillStringTensorElement(), Ort::detail::AllocatorImpl< T >::Free(), Ort::detail::AllocatorImpl< T >::GetAllocation(), Ort::detail::MemoryInfoImpl< T >::GetAllocatorName(), Ort::detail::MemoryInfoImpl< T >::GetAllocatorType(), Ort::detail::attr_utils::GetAttr(), Ort::detail::attr_utils::GetAttrs(), GetAvailableProviders(), Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry(), Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated(), Ort::detail::MemoryInfoImpl< T >::GetDeviceId(), Ort::detail::MemoryInfoImpl< T >::GetDeviceType(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType(), Ort::Status::GetErrorCode(), Ort::Status::GetErrorMessage(), Ort::KernelContext::GetGPUComputeStream(), Ort::ModelMetadata::GetGraphDescriptionAllocated(), Ort::ModelMetadata::GetGraphNameAllocated(), Ort::detail::AllocatorImpl< T >::GetInfo(), Ort::KernelContext::GetInputCount(), Ort::detail::KernelInfoImpl< T >::GetInputCount(), Ort::detail::KernelInfoImpl< T >::GetInputName(), Ort::detail::ConstSessionImpl< T >::GetInputNameAllocated(), Ort::detail::ConstSessionImpl< T >::GetInputTypeInfo(), Ort::detail::KernelInfoImpl< T >::GetInputTypeInfo(), Ort::detail::MapTypeInfoImpl< T >::GetMapKeyType(), Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo(), Ort::detail::TypeInfoImpl< OrtTypeInfo >::GetMapTypeInfo(), Ort::detail::MapTypeInfoImpl< T >::GetMapValueType(), Ort::detail::MemoryInfoImpl< T >::GetMemoryType(), Ort::detail::ConstSessionImpl< T >::GetModelMetadata(), Ort::detail::TypeInfoImpl< T >::GetONNXType(), Ort::detail::ConstValueImpl< T >::GetOpaqueData(), Ort::KernelContext::GetOutput(), Ort::detail::ConstSessionImpl< T >::GetOutputCount(), Ort::KernelContext::GetOutputCount(), Ort::detail::KernelInfoImpl< T >::GetOutputCount(), Ort::detail::KernelInfoImpl< T >::GetOutputName(), Ort::detail::binding_utils::GetOutputNamesHelper(), Ort::detail::binding_utils::GetOutputValuesHelper(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerCount(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerNameAllocated(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerTypeInfo(), Ort::ModelMetadata::GetProducerNameAllocated(), Ort::RunOptions::GetRunLogSeverityLevel(), Ort::RunOptions::GetRunLogVerbosityLevel(), Ort::RunOptions::GetRunTag(), Ort::detail::SequenceTypeInfoImpl< T >::GetSequenceElementType(), Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape(), Ort::detail::ConstValueImpl< T >::GetSparseFormat(), Ort::detail::ConstValueImpl< T >::GetSparseTensorIndicesData(), Ort::detail::ConstValueImpl< T >::GetSparseTensorIndicesTypeShapeInfo(), Ort::detail::ConstValueImpl< T >::GetSparseTensorValues(), Ort::detail::ConstValueImpl< T >::GetSparseTensorValuesTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetStringTensorContent(), Ort::detail::ConstValueImpl< T >::GetStringTensorDataLength(), Ort::detail::ConstValueImpl< T >::GetStringTensorElement(), Ort::detail::ConstValueImpl< T >::GetStringTensorElementLength(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions(), Ort::detail::KernelInfoImpl< OrtKernelInfo >::GetTensorAttribute(), Ort::detail::KernelInfoImpl< T >::GetTensorAttribute(), Ort::detail::ConstValueImpl< T >::GetTensorData(), Ort::detail::ConstValueImpl< T >::GetTensorMemoryInfo(), Ort::detail::ValueImpl< T >::GetTensorMutableData(), Ort::detail::ValueImpl< T >::GetTensorMutableRawData(), Ort::detail::ConstValueImpl< T >::GetTensorRawData(), Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetTensorTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetTypeInfo(), Ort::ModelMetadata::GetVersion(), Ort::Op::Invoke(), Ort::IoBinding::IoBinding(), Ort::detail::ConstValueImpl< T >::IsSparseTensor(), Ort::detail::ConstValueImpl< T >::IsTensor(), Ort::ModelMetadata::LookupCustomMetadataMapAllocated(), Ort::MemoryInfo::MemoryInfo(), Ort::OpAttr::OpAttr(), Ort::detail::MemoryInfoImpl< T >::operator==(), Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary(), Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction(), Ort::detail::SessionImpl< T >::Run(), Ort::RunOptions::RunOptions(), Ort::Session::Session(), Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn(), Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions(), Ort::detail::SessionOptionsImpl< T >::SetExecutionMode(), Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn(), Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn(), Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions(), Ort::ThreadingOptions::SetGlobalDenormalAsZero(), Ort::ThreadingOptions::SetGlobalInterOpNumThreads(), Ort::ThreadingOptions::SetGlobalIntraOpNumThreads(), Ort::ThreadingOptions::SetGlobalSpinControl(), Ort::detail::SessionOptionsImpl< T >::SetLogId(), Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel(), Ort::RunOptions::SetRunLogSeverityLevel(), Ort::RunOptions::SetRunLogVerbosityLevel(), Ort::RunOptions::SetRunTag(), Ort::RunOptions::SetTerminate(), Ort::Status::Status(), Ort::detail::IoBindingImpl< T >::SynchronizeInputs(), Ort::detail::IoBindingImpl< T >::SynchronizeOutputs(), Ort::ThreadingOptions::ThreadingOptions(), Ort::RunOptions::UnsetTerminate(), Ort::Env::UpdateEnvWithCustomLogLevel(), Ort::detail::ValueImpl< T >::UseBlockSparseIndices(), Ort::detail::ValueImpl< T >::UseCooIndices(), Ort::detail::ValueImpl< T >::UseCsrIndices(), and Ort::MemoryAllocation::~MemoryAllocation().
GetAvailableProviders()
std::vector< std::string > Ort::GetAvailableProviders ()
This is a C++ wrapper for OrtApi::GetAvailableProviders() and returns a vector of strings representing the available execution providers.
Returns
vector of strings
References GetApi(), GetAvailableProviders(), and ThrowOnError().
Referenced by GetAvailableProviders().
ThrowOnError() [1/2]
void Ort::ThrowOnError (const Status & st)
References Ort::detail::ThrowStatus().
ThrowOnError() [2/2]
void Ort::ThrowOnError (OrtStatus * ort_status)
References Ort::detail::ThrowStatus().
Referenced by Ort::CustomOpDomain::Add(), Ort::detail::SessionOptionsImpl< T >::Add(), Ort::RunOptions::AddConfigEntry(), Ort::detail::SessionOptionsImpl< T >::AddConfigEntry(), Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers(), Ort::detail::SessionOptionsImpl< T >::AddInitializer(), Ort::detail::AllocatorImpl< T >::Alloc(), Ort::Allocator::Allocator(), Ort::AllocatorWithDefaultOptions::AllocatorWithDefaultOptions(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2(), Ort::detail::SessionOptionsImpl< OrtSessionOptions >::AppendExecutionProvider_MIGraphX(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM(), Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2(), Ort::ArenaCfg::ArenaCfg(), Ort::detail::ValueImpl< T >::At(), Ort::detail::IoBindingImpl< T >::BindInput(), Ort::detail::IoBindingImpl< T >::BindOutput(), Ort::detail::KernelInfoImpl< T >::Copy(), Ort::CustomOpApi::CopyKernelInfo(), Ort::Op::Create(), Ort::Env::CreateAndRegisterAllocator(), Ort::MemoryInfo::CreateCpu(), Ort::Value::CreateMap(), Ort::CustomOpApi::CreateOp(), Ort::Value::CreateOpaque(), Ort::CustomOpApi::CreateOpAttr(), Ort::Value::CreateSequence(), Ort::Value::CreateSparseTensor(), Ort::Value::CreateTensor(), CustomOpApi::KernelInfoGetAttribute< std::string >(), Ort::CustomOpDomain::CustomOpDomain(), Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena(), Ort::detail::SessionOptionsImpl< T >::DisableMemPattern(), Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads(), Ort::detail::SessionOptionsImpl< T >::DisableProfiling(), Ort::Env::DisableTelemetryEvents(), Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena(), Ort::detail::SessionOptionsImpl< T >::EnableMemPattern(), Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps(), Ort::detail::SessionOptionsImpl< T >::EnableProfiling(), Ort::Env::EnableTelemetryEvents(), Ort::detail::SessionImpl< T >::EndProfilingAllocated(), Ort::Env::Env(), Ort::detail::ValueImpl< T >::FillSparseTensorBlockSparse(), Ort::detail::ValueImpl< T >::FillSparseTensorCoo(), Ort::detail::ValueImpl< T >::FillSparseTensorCsr(), Ort::detail::ValueImpl< T >::FillStringTensor(), Ort::detail::ValueImpl< T >::FillStringTensorElement(), Ort::detail::AllocatorImpl< T >::Free(), Ort::detail::AllocatorImpl< T >::GetAllocation(), Ort::detail::MemoryInfoImpl< T >::GetAllocatorName(), Ort::detail::MemoryInfoImpl< T >::GetAllocatorType(), Ort::detail::attr_utils::GetAttr(), Ort::detail::attr_utils::GetAttrs(), GetAvailableProviders(), Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry(), Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated(), Ort::detail::MemoryInfoImpl< T >::GetDeviceId(), Ort::CustomOpApi::GetDimensions(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount(), Ort::CustomOpApi::GetDimensionsCount(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType(), Ort::KernelContext::GetGPUComputeStream(), Ort::ModelMetadata::GetGraphDescriptionAllocated(), Ort::ModelMetadata::GetGraphNameAllocated(), Ort::detail::AllocatorImpl< T >::GetInfo(), Ort::KernelContext::GetInputCount(), Ort::detail::KernelInfoImpl< T >::GetInputCount(), Ort::detail::KernelInfoImpl< T >::GetInputName(), Ort::detail::ConstSessionImpl< T >::GetInputNameAllocated(), Ort::detail::ConstSessionImpl< T >::GetInputTypeInfo(), Ort::detail::KernelInfoImpl< T >::GetInputTypeInfo(), Ort::detail::MapTypeInfoImpl< T >::GetMapKeyType(), Ort::detail::TypeInfoImpl< OrtTypeInfo >::GetMapTypeInfo(), Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo(), Ort::detail::MapTypeInfoImpl< T >::GetMapValueType(), Ort::detail::MemoryInfoImpl< T >::GetMemoryType(), Ort::detail::ConstSessionImpl< T >::GetModelMetadata(), Ort::detail::TypeInfoImpl< T >::GetONNXType(), Ort::detail::ConstValueImpl< T >::GetOpaqueData(), Ort::KernelContext::GetOutput(), Ort::detail::ConstSessionImpl< T >::GetOutputCount(), Ort::KernelContext::GetOutputCount(), Ort::detail::KernelInfoImpl< T >::GetOutputCount(), Ort::detail::KernelInfoImpl< T >::GetOutputName(), Ort::detail::binding_utils::GetOutputNamesHelper(), Ort::detail::binding_utils::GetOutputValuesHelper(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerCount(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerNameAllocated(), Ort::detail::ConstSessionImpl< T >::GetOverridableInitializerTypeInfo(), Ort::ModelMetadata::GetProducerNameAllocated(), Ort::RunOptions::GetRunLogSeverityLevel(), Ort::RunOptions::GetRunLogVerbosityLevel(), Ort::RunOptions::GetRunTag(), Ort::detail::SequenceTypeInfoImpl< T >::GetSequenceElementType(), Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape(), Ort::detail::ConstValueImpl< T >::GetSparseFormat(), Ort::detail::ConstValueImpl< T >::GetSparseTensorIndicesData(), Ort::detail::ConstValueImpl< T >::GetSparseTensorIndicesTypeShapeInfo(), Ort::detail::ConstValueImpl< T >::GetSparseTensorValues(), Ort::detail::ConstValueImpl< T >::GetSparseTensorValuesTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetStringTensorContent(), Ort::detail::ConstValueImpl< T >::GetStringTensorDataLength(), Ort::detail::ConstValueImpl< T >::GetStringTensorElement(), Ort::detail::ConstValueImpl< T >::GetStringTensorElementLength(), Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions(), Ort::detail::KernelInfoImpl< OrtKernelInfo >::GetTensorAttribute(), Ort::detail::KernelInfoImpl< T >::GetTensorAttribute(), Ort::detail::ConstValueImpl< T >::GetTensorData(), Ort::CustomOpApi::GetTensorData(), Ort::CustomOpApi::GetTensorElementType(), Ort::detail::ConstValueImpl< T >::GetTensorMemoryInfo(), Ort::CustomOpApi::GetTensorMemoryInfo(), Ort::detail::ValueImpl< T >::GetTensorMutableData(), Ort::CustomOpApi::GetTensorMutableData(), Ort::detail::ValueImpl< T >::GetTensorMutableRawData(), Ort::detail::ConstValueImpl< T >::GetTensorRawData(), Ort::CustomOpApi::GetTensorShape(), Ort::CustomOpApi::GetTensorShapeElementCount(), Ort::CustomOpApi::GetTensorTypeAndShape(), Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetTensorTypeAndShapeInfo(), Ort::detail::ConstValueImpl< T >::GetTypeInfo(), Ort::ModelMetadata::GetVersion(), Ort::Op::Invoke(), Ort::CustomOpApi::InvokeOp(), Ort::IoBinding::IoBinding(), Ort::detail::ConstValueImpl< T >::IsSparseTensor(), Ort::detail::ConstValueImpl< T >::IsTensor(), Ort::CustomOpApi::KernelContext_GetGPUComputeStream(), Ort::CustomOpApi::KernelContext_GetInput(), Ort::CustomOpApi::KernelContext_GetInputCount(), Ort::CustomOpApi::KernelContext_GetOutput(), Ort::CustomOpApi::KernelContext_GetOutputCount(), Ort::CustomOpApi::KernelInfoGetAttribute(), Ort::ModelMetadata::LookupCustomMetadataMapAllocated(), Ort::MemoryInfo::MemoryInfo(), Ort::OpAttr::OpAttr(), Ort::detail::MemoryInfoImpl< T >::operator==(), Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary(), Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction(), Ort::detail::SessionImpl< T >::Run(), Ort::RunOptions::RunOptions(), Ort::Session::Session(), Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn(), Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions(), Ort::CustomOpApi::SetDimensions(), Ort::detail::SessionOptionsImpl< T >::SetExecutionMode(), Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn(), Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn(), Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions(), Ort::ThreadingOptions::SetGlobalDenormalAsZero(), Ort::ThreadingOptions::SetGlobalInterOpNumThreads(), Ort::ThreadingOptions::SetGlobalIntraOpNumThreads(), Ort::ThreadingOptions::SetGlobalSpinControl(), Ort::detail::SessionOptionsImpl< T >::SetLogId(), Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel(), Ort::RunOptions::SetRunLogSeverityLevel(), Ort::RunOptions::SetRunLogVerbosityLevel(), Ort::RunOptions::SetRunTag(), Ort::RunOptions::SetTerminate(), Ort::detail::IoBindingImpl< T >::SynchronizeInputs(), Ort::detail::IoBindingImpl< T >::SynchronizeOutputs(), Ort::ThreadingOptions::ThreadingOptions(), Ort::CustomOpApi::ThrowOnError(), Ort::RunOptions::UnsetTerminate(), Ort::Env::UpdateEnvWithCustomLogLevel(), Ort::detail::ValueImpl< T >::UseBlockSparseIndices(), Ort::detail::ValueImpl< T >::UseCooIndices(), and Ort::detail::ValueImpl< T >::UseCsrIndices().