CI-FirstResponders: Ort::detail Namespace Reference
Ort::detail Namespace Reference
Namespaces
namespace attr_utils
namespace binding_utils
Classes
struct AllocatedFree
struct AllocatorImpl
struct Base
Used internally by the C++ API. C++ wrapper types inherit from this. This is a zero cost abstraction to wrap the C API objects and delete them on destruction.
struct Base< Unowned< T > >
Covers unowned pointers owned by either the ORT or some other instance of CPP wrappers. Used for ConstXXX and UnownedXXXX types that are copyable. Also convenient to wrap raw OrtXX pointers .
struct ConstIoBindingImpl
struct ConstSessionImpl
struct ConstSessionOptionsImpl
struct ConstValueImpl
struct IoBindingImpl
struct KernelInfoImpl
struct MapTypeInfoImpl
struct MemoryInfoImpl
struct OrtSparseValuesParam
struct SequenceTypeInfoImpl
struct SessionImpl
struct SessionOptionsImpl
struct Shape
struct TensorTypeAndShapeInfoImpl
struct TypeInfoImpl
struct Unowned
This is a tagging template type. Use it with Base<T> to indicate that the C++ interface object has no ownership of the underlying C object.
struct ValueImpl
Functions
ORT_DEFINE_RELEASE (Allocator)
ORT_DEFINE_RELEASE (MemoryInfo)
ORT_DEFINE_RELEASE (CustomOpDomain)
ORT_DEFINE_RELEASE (ThreadingOptions)
ORT_DEFINE_RELEASE (Env)
ORT_DEFINE_RELEASE (RunOptions)
ORT_DEFINE_RELEASE (Session)
ORT_DEFINE_RELEASE (SessionOptions)
ORT_DEFINE_RELEASE (TensorTypeAndShapeInfo)
ORT_DEFINE_RELEASE (SequenceTypeInfo)
ORT_DEFINE_RELEASE (MapTypeInfo)
ORT_DEFINE_RELEASE (TypeInfo)
ORT_DEFINE_RELEASE (Value)
ORT_DEFINE_RELEASE (ModelMetadata)
ORT_DEFINE_RELEASE (IoBinding)
ORT_DEFINE_RELEASE (ArenaCfg)
ORT_DEFINE_RELEASE (Status)
ORT_DEFINE_RELEASE (OpAttr)
ORT_DEFINE_RELEASE (Op)
ORT_DEFINE_RELEASE (KernelInfo)
std::string MakeCustomOpConfigEntryKey (const char *custom_op_name, const char *config)
CustomOpConfigs.
void ThrowStatus (const Status &st)
Function Documentation
MakeCustomOpConfigEntryKey()
std::string Ort::detail::MakeCustomOpConfigEntryKey (const char * custom_op_name, const char * config)
CustomOpConfigs.
Referenced by Ort::CustomOpConfigs::AddConfig(), and Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs().
ORT_DEFINE_RELEASE() [1/20]
Ort::detail::ORT_DEFINE_RELEASE (Allocator)
ORT_DEFINE_RELEASE() [2/20]
Ort::detail::ORT_DEFINE_RELEASE (ArenaCfg)
ORT_DEFINE_RELEASE() [3/20]
Ort::detail::ORT_DEFINE_RELEASE (CustomOpDomain)
ORT_DEFINE_RELEASE() [4/20]
Ort::detail::ORT_DEFINE_RELEASE (Env)
ORT_DEFINE_RELEASE() [5/20]
Ort::detail::ORT_DEFINE_RELEASE (IoBinding)
ORT_DEFINE_RELEASE() [6/20]
Ort::detail::ORT_DEFINE_RELEASE (KernelInfo)
ORT_DEFINE_RELEASE() [7/20]
Ort::detail::ORT_DEFINE_RELEASE (MapTypeInfo)
ORT_DEFINE_RELEASE() [8/20]
Ort::detail::ORT_DEFINE_RELEASE (MemoryInfo)
ORT_DEFINE_RELEASE() [9/20]
Ort::detail::ORT_DEFINE_RELEASE (ModelMetadata)
ORT_DEFINE_RELEASE() [10/20]
Ort::detail::ORT_DEFINE_RELEASE (Op)
ORT_DEFINE_RELEASE() [11/20]
Ort::detail::ORT_DEFINE_RELEASE (OpAttr)
ORT_DEFINE_RELEASE() [12/20]
Ort::detail::ORT_DEFINE_RELEASE (RunOptions)
ORT_DEFINE_RELEASE() [13/20]
Ort::detail::ORT_DEFINE_RELEASE (SequenceTypeInfo)
ORT_DEFINE_RELEASE() [14/20]
Ort::detail::ORT_DEFINE_RELEASE (Session)
ORT_DEFINE_RELEASE() [15/20]
Ort::detail::ORT_DEFINE_RELEASE (SessionOptions)
ORT_DEFINE_RELEASE() [16/20]
Ort::detail::ORT_DEFINE_RELEASE (Status)
ORT_DEFINE_RELEASE() [17/20]
Ort::detail::ORT_DEFINE_RELEASE (TensorTypeAndShapeInfo)
ORT_DEFINE_RELEASE() [18/20]
Ort::detail::ORT_DEFINE_RELEASE (ThreadingOptions)
ORT_DEFINE_RELEASE() [19/20]
Ort::detail::ORT_DEFINE_RELEASE (TypeInfo)
ORT_DEFINE_RELEASE() [20/20]
Ort::detail::ORT_DEFINE_RELEASE (Value)
ThrowStatus()
void Ort::detail::ThrowStatus (const Status & st)
References Ort::Status::GetErrorCode(), Ort::Status::GetErrorMessage(), and ORT_CXX_API_THROW.
Referenced by Ort::ThrowOnError().