CI-FirstResponders: Ort::KernelContext Struct Reference
Ort::KernelContext Struct Reference
This class wraps a raw pointer OrtKernelContext* that is being passed to the custom kernel Compute() method. Use it to safely access context attributes, input and output parameters with exception safety guarantees. See usage example in onnxruntime/test/testdata/custom_op_library/custom_op_library.cc.
#include <onnxruntime_cxx_api.h>
Public Member Functions
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
KernelContext (OrtKernelContext *context)
size_t GetInputCount () const
size_t GetOutputCount () const
ConstValue GetInput (size_t index) const
UnownedValue GetOutput (size_t index, const int64_t *dim_values, size_t dim_count) const
UnownedValue GetOutput (size_t index, const std::vector< int64_t > &dims) const
void * GetGPUComputeStream () const
Detailed Description
This class wraps a raw pointer OrtKernelContext* that is being passed to the custom kernel Compute() method. Use it to safely access context attributes, input and output parameters with exception safety guarantees. See usage example in onnxruntime/test/testdata/custom_op_library/custom_op_library.cc.
Constructor & Destructor Documentation
KernelContext() [1/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [2/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [3/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [4/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [5/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [6/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
KernelContext() [7/7]
Ort::KernelContext::KernelContext (OrtKernelContext * context) explicit
Member Function Documentation
GetGPUComputeStream() [1/7]
void * Ort::KernelContext::GetGPUComputeStream () const
References Ort::GetApi(), and Ort::ThrowOnError().
GetGPUComputeStream() [2/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetGPUComputeStream() [3/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetGPUComputeStream() [4/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetGPUComputeStream() [5/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetGPUComputeStream() [6/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetGPUComputeStream() [7/7]
void * Ort::KernelContext::GetGPUComputeStream () const
GetInput() [1/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [2/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [3/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [4/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [5/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [6/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInput() [7/7]
ConstValue Ort::KernelContext::GetInput (size_t index) const
GetInputCount() [1/7]
size_t Ort::KernelContext::GetInputCount () const
References Ort::GetApi(), and Ort::ThrowOnError().
GetInputCount() [2/7]
size_t Ort::KernelContext::GetInputCount () const
GetInputCount() [3/7]
size_t Ort::KernelContext::GetInputCount () const
GetInputCount() [4/7]
size_t Ort::KernelContext::GetInputCount () const
GetInputCount() [5/7]
size_t Ort::KernelContext::GetInputCount () const
GetInputCount() [6/7]
size_t Ort::KernelContext::GetInputCount () const
GetInputCount() [7/7]
size_t Ort::KernelContext::GetInputCount () const
GetOutput() [1/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [2/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [3/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [4/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [5/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [6/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [7/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const int64_t * dim_values, size_t dim_count) const
GetOutput() [8/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
References Ort::GetApi(), and Ort::ThrowOnError().
GetOutput() [9/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutput() [10/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutput() [11/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutput() [12/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutput() [13/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutput() [14/14]
UnownedValue Ort::KernelContext::GetOutput (size_t index, const std::vector< int64_t > & dims) const
GetOutputCount() [1/7]
size_t Ort::KernelContext::GetOutputCount () const
References Ort::GetApi(), and Ort::ThrowOnError().
GetOutputCount() [2/7]
size_t Ort::KernelContext::GetOutputCount () const
GetOutputCount() [3/7]
size_t Ort::KernelContext::GetOutputCount () const
GetOutputCount() [4/7]
size_t Ort::KernelContext::GetOutputCount () const
GetOutputCount() [5/7]
size_t Ort::KernelContext::GetOutputCount () const
GetOutputCount() [6/7]
size_t Ort::KernelContext::GetOutputCount () const
GetOutputCount() [7/7]
size_t Ort::KernelContext::GetOutputCount () const
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h