CI-FirstResponders: Ort::Env Struct Reference
Ort::Env Struct Reference
The Env (Environment)
#include <onnxruntime_cxx_api.h>
Public Member Functions
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Env (std::nullptr_t)
Create an empty Env object, must be assigned a valid one to be used.
Env (OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnv.
Env (OrtLoggingLevel logging_level, const char *logid, OrtLoggingFunction logging_function, void *logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env (const OrtThreadingOptions *tp_options, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env (const OrtThreadingOptions *tp_options, OrtLoggingFunction logging_function, void *logger_param, OrtLoggingLevel logging_level=ORT_LOGGING_LEVEL_WARNING, _In_ const char *logid="")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env (OrtEnv *p)
C Interop Helper.
Env & EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
Env & DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
Env & UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
Env & CreateAndRegisterAllocator (const OrtMemoryInfo *mem_info, const OrtArenaCfg *arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
Public Member Functions inherited from Ort::detail::Base< OrtEnv >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtEnv >
using contained_type = OrtEnv
using contained_type = OrtEnv
using contained_type = OrtEnv
using contained_type = OrtEnv
using contained_type = OrtEnv
using contained_type = OrtEnv
using contained_type = OrtEnv
Protected Attributes inherited from Ort::detail::Base< OrtEnv >
contained_type * p_
Detailed Description
The Env (Environment)
The Env holds the logging state used by all other objects. Note: One Env must be created before using any other Onnxruntime functionality
Constructor & Destructor Documentation
Env() [1/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [2/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
References Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Env() [3/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
References Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Env() [4/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
References Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Env() [5/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
References Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Env() [6/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [7/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [8/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [9/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [10/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [11/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [12/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [13/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [14/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [15/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [16/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [17/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [18/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [19/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [20/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [21/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [22/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [23/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [24/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [25/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [26/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [27/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [28/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [29/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [30/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [31/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [32/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [33/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [34/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [35/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [36/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Env() [37/42]
Ort::Env::Env (std::nullptr_t) explicit
Create an empty Env object, must be assigned a valid one to be used.
Env() [38/42]
Ort::Env::Env (OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnv.
Env() [39/42]
Ort::Env::Env (OrtLoggingLevel logging_level, const char * logid, OrtLoggingFunction logging_function, void * logger_param)
Wraps OrtApi::CreateEnvWithCustomLogger.
Env() [40/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithGlobalThreadPools.
Env() [41/42]
Ort::Env::Env (const OrtThreadingOptions * tp_options, OrtLoggingFunction logging_function, void * logger_param, OrtLoggingLevel logging_level = ORT_LOGGING_LEVEL_WARNING, _In_ const char * logid = "")
Wraps OrtApi::CreateEnvWithCustomLoggerAndGlobalThreadPools.
Env() [42/42]
Ort::Env::Env (OrtEnv * p) explicit
C Interop Helper.
Member Function Documentation
CreateAndRegisterAllocator() [1/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
References CreateAndRegisterAllocator(), Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Referenced by CreateAndRegisterAllocator().
CreateAndRegisterAllocator() [2/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
CreateAndRegisterAllocator() [3/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
CreateAndRegisterAllocator() [4/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
CreateAndRegisterAllocator() [5/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
CreateAndRegisterAllocator() [6/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
CreateAndRegisterAllocator() [7/7]
Env & Ort::Env::CreateAndRegisterAllocator (const OrtMemoryInfo * mem_info, const OrtArenaCfg * arena_cfg)
Wraps OrtApi::CreateAndRegisterAllocator.
DisableTelemetryEvents() [1/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
References DisableTelemetryEvents(), Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Referenced by DisableTelemetryEvents().
DisableTelemetryEvents() [2/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
DisableTelemetryEvents() [3/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
DisableTelemetryEvents() [4/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
DisableTelemetryEvents() [5/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
DisableTelemetryEvents() [6/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
DisableTelemetryEvents() [7/7]
Env & Ort::Env::DisableTelemetryEvents ()
Wraps OrtApi::DisableTelemetryEvents.
EnableTelemetryEvents() [1/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
References EnableTelemetryEvents(), Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, and Ort::ThrowOnError().
Referenced by EnableTelemetryEvents().
EnableTelemetryEvents() [2/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
EnableTelemetryEvents() [3/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
EnableTelemetryEvents() [4/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
EnableTelemetryEvents() [5/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
EnableTelemetryEvents() [6/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
EnableTelemetryEvents() [7/7]
Env & Ort::Env::EnableTelemetryEvents ()
Wraps OrtApi::EnableTelemetryEvents.
UpdateEnvWithCustomLogLevel() [1/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
References Ort::GetApi(), Ort::detail::Base< OrtEnv >::p_, Ort::ThrowOnError(), and UpdateEnvWithCustomLogLevel().
Referenced by UpdateEnvWithCustomLogLevel().
UpdateEnvWithCustomLogLevel() [2/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
UpdateEnvWithCustomLogLevel() [3/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
UpdateEnvWithCustomLogLevel() [4/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
UpdateEnvWithCustomLogLevel() [5/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
UpdateEnvWithCustomLogLevel() [6/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
UpdateEnvWithCustomLogLevel() [7/7]
Env & Ort::Env::UpdateEnvWithCustomLogLevel (OrtLoggingLevel log_severity_level)
Wraps OrtApi::UpdateEnvWithCustomLogLevel.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h