CI-FirstResponders: Ort::detail::SessionImpl< T > Struct Template Reference
Ort::detail::SessionImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = ConstSessionImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::ConstSessionImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
Public Member Functions inherited from Ort::detail::ConstSessionImpl< T >
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [2/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [3/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [4/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [5/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [6/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [7/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [8/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [9/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [10/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [11/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [12/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [13/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [14/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [15/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [16/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [17/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [18/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [19/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [20/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [21/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [22/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [23/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [24/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [25/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [26/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [27/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [28/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [29/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [30/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [31/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [32/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [33/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [34/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [35/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [36/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [37/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [38/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [39/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [40/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [41/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [42/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [43/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [44/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [45/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [46/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [47/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [48/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [49/56]
template<typename T > using Ort::detail::SessionImpl< T >::B = ConstSessionImpl<T>
B [50/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [51/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [52/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [53/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [54/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [55/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
B [56/56]
template<typename T > using Ort::detail::ConstSessionImpl< T >::B = Base<T>
Member Function Documentation
EndProfilingAllocated() [1/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
References Ort::GetApi(), and Ort::ThrowOnError().
EndProfilingAllocated() [2/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
EndProfilingAllocated() [3/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
EndProfilingAllocated() [4/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
EndProfilingAllocated() [5/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
EndProfilingAllocated() [6/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
EndProfilingAllocated() [7/7]
template<typename T > AllocatedStringPtr Ort::detail::SessionImpl< T >::EndProfilingAllocated (OrtAllocator * allocator)
End profiling and return a copy of the profiling file name.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::SessionEndProfiling
Run() [1/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [2/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [3/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [4/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [5/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [6/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [7/21]
template<typename T > std::vector< Value > Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
Wraps OrtApi::Run
The caller provides a list of inputs and a list of the desired outputs to return.
See the output logs for more information on warnings/errors that occur while processing the model. Common errors are.. (TODO)
Parameters
[in] run_options
[in] input_names Array of null terminated strings of length input_count that is the list of input names
[in] input_values Array of Value objects of length input_count that is the list of input values
[in] input_count Number of inputs (the size of the input_names & input_values arrays)
[in] output_names Array of C style strings of length output_count that is the list of output names
[in] output_count Number of outputs (the size of the output_names array)
Returns
A std::vector of Value objects that directly maps to the output_names array (eg. output_name[0] is the first entry of the returned vector)
Run() [8/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
References Ort::GetApi(), and Ort::ThrowOnError().
Run() [9/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [10/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [11/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [12/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [13/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [14/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const char *const * input_names, const Value * input_values, size_t input_count, const char *const * output_names, Value * output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
Run() [15/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding & io_binding)
Wraps OrtApi::RunWithBinding.
References Ort::GetApi(), and Ort::ThrowOnError().
Run() [16/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
Run() [17/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
Run() [18/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
Run() [19/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
Run() [20/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
Run() [21/21]
template<typename T > void Ort::detail::SessionImpl< T >::Run (const RunOptions & run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h