CI-FirstResponders: Ort::detail::SessionOptionsImpl< T > Struct Template Reference
Ort::detail::SessionOptionsImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = ConstSessionOptionsImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::ConstSessionOptionsImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SessionOptionsImpl & SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SessionOptionsImpl & SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SessionOptionsImpl & SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SessionOptionsImpl & EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
SessionOptionsImpl & DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
SessionOptionsImpl & SetOptimizedModelFilePath (const ORTCHAR_T *optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SessionOptionsImpl & EnableProfiling (const ORTCHAR_T *profile_file_prefix)
Wraps OrtApi::EnableProfiling.
SessionOptionsImpl & DisableProfiling ()
Wraps OrtApi::DisableProfiling.
SessionOptionsImpl & EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
SessionOptionsImpl & EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
SessionOptionsImpl & DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
SessionOptionsImpl & SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SessionOptionsImpl & SetLogId (const char *logid)
Wraps OrtApi::SetSessionLogId.
SessionOptionsImpl & SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SessionOptionsImpl & Add (OrtCustomOpDomain *custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
SessionOptionsImpl & DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
SessionOptionsImpl & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddSessionConfigEntry.
SessionOptionsImpl & AddInitializer (const char *name, const OrtValue *ort_val)
Wraps OrtApi::AddInitializer.
SessionOptionsImpl & AddExternalInitializers (const std::vector< std::string > &names, const std::vector< Value > &ort_values)
Wraps OrtApi::AddExternalInitializers.
SessionOptionsImpl & AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
SessionOptionsImpl & AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
SessionOptionsImpl & AppendExecutionProvider_ROCM (const OrtROCMProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
SessionOptionsImpl & AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
SessionOptionsImpl & AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
SessionOptionsImpl & AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions &provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
SessionOptionsImpl & AppendExecutionProvider_CANN (const OrtCANNProviderOptions &provider_options)
SessionOptionsImpl & AppendExecutionProvider (const std::string &provider_name, const std::unordered_map< std::string, std::string > &provider_options={})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
SessionOptionsImpl & SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SessionOptionsImpl & SetCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SessionOptionsImpl & SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
SessionOptionsImpl & RegisterCustomOpsLibrary (const ORTCHAR_T *library_name, const CustomOpConfigs &custom_op_configs={})
SessionOptionsImpl & RegisterCustomOpsUsingFunction (const char *function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
Public Member Functions inherited from Ort::detail::ConstSessionOptionsImpl< T >
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [2/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [3/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [4/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [5/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [6/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [7/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [8/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [9/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [10/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [11/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [12/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [13/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [14/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [15/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [16/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [17/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [18/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [19/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [20/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [21/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [22/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [23/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [24/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [25/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [26/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [27/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [28/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [29/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [30/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [31/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [32/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [33/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [34/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [35/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [36/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [37/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [38/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [39/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [40/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [41/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [42/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [43/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [44/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [45/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [46/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [47/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [48/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [49/56]
template<typename T > using Ort::detail::SessionOptionsImpl< T >::B = ConstSessionOptionsImpl<T>
B [50/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [51/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [52/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [53/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [54/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [55/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [56/56]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
Member Function Documentation
Add() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
References Ort::GetApi(), and Ort::ThrowOnError().
Add() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
Add() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
Add() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
Add() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
Add() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
Add() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::Add (OrtCustomOpDomain * custom_op_domain)
Wraps OrtApi::AddCustomOpDomain.
AddConfigEntry() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
References Ort::GetApi(), and Ort::ThrowOnError().
AddConfigEntry() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddConfigEntry() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddConfigEntry() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddConfigEntry() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddConfigEntry() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddConfigEntry() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddSessionConfigEntry.
AddExternalInitializers() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
References Ort::GetApi(), ORT_CXX_API_THROW, ORT_INVALID_ARGUMENT, and Ort::ThrowOnError().
AddExternalInitializers() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddExternalInitializers() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddExternalInitializers() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddExternalInitializers() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddExternalInitializers() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddExternalInitializers() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddExternalInitializers (const std::vector< std::string > & names, const std::vector< Value > & ort_values)
Wraps OrtApi::AddExternalInitializers.
AddInitializer() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
References Ort::AddInitializer(), Ort::GetApi(), and Ort::ThrowOnError().
AddInitializer() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AddInitializer() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AddInitializer() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AddInitializer() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AddInitializer() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AddInitializer() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AddInitializer (const char * name, const OrtValue * ort_val)
Wraps OrtApi::AddInitializer.
AppendExecutionProvider() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider (const std::string & provider_name, const std::unordered_map< std::string, std::string > & provider_options = {})
Wraps OrtApi::SessionOptionsAppendExecutionProvider. Currently supports SNPE and XNNPACK.
AppendExecutionProvider_CANN() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider_CANN() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CANN() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CANN() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CANN() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CANN() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CANN() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CANN (const OrtCANNProviderOptions & provider_options)
AppendExecutionProvider_CUDA() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA (const OrtCUDAProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA.
AppendExecutionProvider_CUDA_V2() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider_CUDA_V2() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_CUDA_V2() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_CUDA_V2() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_CUDA_V2() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_CUDA_V2() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_CUDA_V2() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_CUDA_V2 (const OrtCUDAProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CUDA_V2.
AppendExecutionProvider_MIGraphX() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_MIGraphX() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_MIGraphX (const OrtMIGraphXProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_CANN.
Wraps OrtApi::SessionOptionsAppendExecutionProvider_MIGraphX
AppendExecutionProvider_OpenVINO() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider_OpenVINO() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_OpenVINO() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_OpenVINO() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_OpenVINO() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_OpenVINO() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_OpenVINO() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_OpenVINO (const OrtOpenVINOProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_OpenVINO.
AppendExecutionProvider_ROCM() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider_ROCM() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_ROCM() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_ROCM() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_ROCM() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_ROCM() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_ROCM() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_ROCM (const OrtROCMProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_ROCM.
AppendExecutionProvider_TensorRT() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT (const OrtTensorRTProviderOptions & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
References Ort::GetApi(), and Ort::ThrowOnError().
AppendExecutionProvider_TensorRT_V2() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
AppendExecutionProvider_TensorRT_V2() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::AppendExecutionProvider_TensorRT_V2 (const OrtTensorRTProviderOptionsV2 & provider_options)
Wraps OrtApi::SessionOptionsAppendExecutionProvider_TensorRT.
DisableCpuMemArena() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena
Wraps OrtApi::DisableCpuMemArena.
References Ort::GetApi(), and Ort::ThrowOnError().
DisableCpuMemArena() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableCpuMemArena() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableCpuMemArena() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableCpuMemArena() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableCpuMemArena() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableCpuMemArena() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableCpuMemArena ()
Wraps OrtApi::DisableCpuMemArena.
DisableMemPattern() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern
Wraps OrtApi::DisableMemPattern.
References Ort::GetApi(), and Ort::ThrowOnError().
DisableMemPattern() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisableMemPattern() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisableMemPattern() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisableMemPattern() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisableMemPattern() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisableMemPattern() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableMemPattern ()
Wraps OrtApi::DisableMemPattern.
DisablePerSessionThreads() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads
Wraps OrtApi::DisablePerSessionThreads.
References Ort::GetApi(), and Ort::ThrowOnError().
DisablePerSessionThreads() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisablePerSessionThreads() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisablePerSessionThreads() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisablePerSessionThreads() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisablePerSessionThreads() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisablePerSessionThreads() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisablePerSessionThreads ()
Wraps OrtApi::DisablePerSessionThreads.
DisableProfiling() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::DisableProfiling
Wraps OrtApi::DisableProfiling.
References Ort::GetApi(), and Ort::ThrowOnError().
DisableProfiling() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
DisableProfiling() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
DisableProfiling() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
DisableProfiling() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
DisableProfiling() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
DisableProfiling() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::DisableProfiling ()
Wraps OrtApi::DisableProfiling.
EnableCpuMemArena() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena
Wraps OrtApi::EnableCpuMemArena.
References Ort::GetApi(), and Ort::ThrowOnError().
EnableCpuMemArena() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableCpuMemArena() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableCpuMemArena() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableCpuMemArena() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableCpuMemArena() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableCpuMemArena() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableCpuMemArena ()
Wraps OrtApi::EnableCpuMemArena.
EnableMemPattern() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern
Wraps OrtApi::EnableMemPattern.
References Ort::GetApi(), and Ort::ThrowOnError().
EnableMemPattern() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableMemPattern() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableMemPattern() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableMemPattern() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableMemPattern() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableMemPattern() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableMemPattern ()
Wraps OrtApi::EnableMemPattern.
EnableOrtCustomOps() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps
Wraps OrtApi::EnableOrtCustomOps.
References Ort::GetApi(), and Ort::ThrowOnError().
EnableOrtCustomOps() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableOrtCustomOps() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableOrtCustomOps() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableOrtCustomOps() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableOrtCustomOps() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableOrtCustomOps() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableOrtCustomOps ()
Wraps OrtApi::EnableOrtCustomOps.
EnableProfiling() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
References Ort::GetApi(), and Ort::ThrowOnError().
EnableProfiling() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
EnableProfiling() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
EnableProfiling() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
EnableProfiling() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
EnableProfiling() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
EnableProfiling() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::EnableProfiling (const ORTCHAR_T * profile_file_prefix)
Wraps OrtApi::EnableProfiling.
RegisterCustomOpsLibrary() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
References Ort::GetApi(), Ort::CustomOpConfigs::GetFlattenedConfigs(), and Ort::ThrowOnError().
RegisterCustomOpsLibrary() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsLibrary() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsLibrary() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsLibrary() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsLibrary() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsLibrary() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsLibrary (const ORTCHAR_T * library_name, const CustomOpConfigs & custom_op_configs = {})
RegisterCustomOpsUsingFunction() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
References Ort::GetApi(), and Ort::ThrowOnError().
RegisterCustomOpsUsingFunction() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
RegisterCustomOpsUsingFunction() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
RegisterCustomOpsUsingFunction() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
RegisterCustomOpsUsingFunction() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
RegisterCustomOpsUsingFunction() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
RegisterCustomOpsUsingFunction() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::RegisterCustomOpsUsingFunction (const char * function_name)
Wraps OrtApi::RegisterCustomOpsUsingFunction.
SetCustomCreateThreadFn() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
References Ort::GetApi(), and Ort::ThrowOnError().
SetCustomCreateThreadFn() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomCreateThreadFn() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomCreateThreadFn() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomCreateThreadFn() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomCreateThreadFn() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomCreateThreadFn() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomCreateThreadFn.
SetCustomJoinThreadFn() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomJoinThreadFn() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SessionOptionsSetCustomJoinThreadFn.
Registers the custom operator from the specified shared library via OrtApi::RegisterCustomOpsLibrary_V2. The custom operator configurations are optional. If provided, custom operator configs are set via OrtApi::AddSessionConfigEntry.
SetCustomThreadCreationOptions() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
References Ort::GetApi(), and Ort::ThrowOnError().
SetCustomThreadCreationOptions() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetCustomThreadCreationOptions() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetCustomThreadCreationOptions() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetCustomThreadCreationOptions() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetCustomThreadCreationOptions() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetCustomThreadCreationOptions() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SessionOptionsSetCustomThreadCreationOptions.
SetExecutionMode() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
References Ort::GetApi(), and Ort::ThrowOnError().
SetExecutionMode() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetExecutionMode() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetExecutionMode() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetExecutionMode() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetExecutionMode() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetExecutionMode() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetExecutionMode (ExecutionMode execution_mode)
Wraps OrtApi::SetSessionExecutionMode.
SetGraphOptimizationLevel() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetGraphOptimizationLevel() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetGraphOptimizationLevel (GraphOptimizationLevel graph_optimization_level)
Wraps OrtApi::SetSessionGraphOptimizationLevel.
SetInterOpNumThreads() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetInterOpNumThreads() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetInterOpNumThreads.
SetIntraOpNumThreads() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetIntraOpNumThreads() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetIntraOpNumThreads.
SetLogId() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
References Ort::GetApi(), and Ort::ThrowOnError().
SetLogId() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogId() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogId() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogId() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogId() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogId() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogId (const char * logid)
Wraps OrtApi::SetSessionLogId.
SetLogSeverityLevel() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
References Ort::GetApi(), and Ort::ThrowOnError().
SetLogSeverityLevel() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetLogSeverityLevel() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetLogSeverityLevel() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetLogSeverityLevel() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetLogSeverityLevel() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetLogSeverityLevel() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetLogSeverityLevel (int level)
Wraps OrtApi::SetSessionLogSeverityLevel.
SetOptimizedModelFilePath() [1/7]
template<typename T > SessionOptionsImpl< T > & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [2/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [3/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [4/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [5/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [6/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
SetOptimizedModelFilePath() [7/7]
template<typename T > SessionOptionsImpl & Ort::detail::SessionOptionsImpl< T >::SetOptimizedModelFilePath (const ORTCHAR_T * optimized_model_file)
Wraps OrtApi::SetOptimizedModelFilePath.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h