CI-FirstResponders: Ort::CustomOpBase< TOp, TKernel > Struct Template Reference
Ort::CustomOpBase< TOp, TKernel > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Member Functions
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
CustomOpBase ()
const char * GetExecutionProviderType () const
OrtCustomOpInputOutputCharacteristic GetInputCharacteristic (size_t) const
OrtCustomOpInputOutputCharacteristic GetOutputCharacteristic (size_t) const
OrtMemType GetInputMemoryType (size_t) const
int GetVariadicInputMinArity () const
bool GetVariadicInputHomogeneity () const
int GetVariadicOutputMinArity () const
bool GetVariadicOutputHomogeneity () const
std::vector< std::string > GetSessionConfigKeys () const
Public Member Functions inherited from OrtCustomOp
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
Protected Member Functions
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
void GetSessionConfigs (std::unordered_map< std::string, std::string > &out, ConstSessionOptions options) const
Additional Inherited Members
Public Attributes inherited from OrtCustomOp
uint32_t version
_In_ size_t index
_In_ OrtKernelContext * context
Constructor & Destructor Documentation
CustomOpBase() [1/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [2/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [3/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [4/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [5/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [6/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
CustomOpBase() [7/7]
template<typename TOp , typename TKernel > Ort::CustomOpBase< TOp, TKernel >::CustomOpBase ()
References OrtCustomOp::context, OrtCustomOp::CreateKernel(), Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType(), OrtCustomOp::GetExecutionProviderType(), Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType(), OrtCustomOp::GetName(), Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity(), Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity(), OrtCustomOp::index, ORT_API_VERSION, and OrtCustomOp::version.
Member Function Documentation
GetExecutionProviderType() [1/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetExecutionProviderType() [2/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetExecutionProviderType() [3/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetExecutionProviderType() [4/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetExecutionProviderType() [5/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetExecutionProviderType() [6/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetExecutionProviderType() [7/7]
template<typename TOp , typename TKernel > const char * Ort::CustomOpBase< TOp, TKernel >::GetExecutionProviderType () const
GetInputCharacteristic() [1/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetInputCharacteristic() [2/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputCharacteristic() [3/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputCharacteristic() [4/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputCharacteristic() [5/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputCharacteristic() [6/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputCharacteristic() [7/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetInputCharacteristic (size_t) const
GetInputMemoryType() [1/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetInputMemoryType() [2/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetInputMemoryType() [3/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetInputMemoryType() [4/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetInputMemoryType() [5/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetInputMemoryType() [6/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetInputMemoryType() [7/7]
template<typename TOp , typename TKernel > OrtMemType Ort::CustomOpBase< TOp, TKernel >::GetInputMemoryType (size_t) const
References OrtMemTypeDefault.
GetOutputCharacteristic() [1/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetOutputCharacteristic() [2/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetOutputCharacteristic() [3/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetOutputCharacteristic() [4/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetOutputCharacteristic() [5/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetOutputCharacteristic() [6/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetOutputCharacteristic() [7/7]
template<typename TOp , typename TKernel > OrtCustomOpInputOutputCharacteristic Ort::CustomOpBase< TOp, TKernel >::GetOutputCharacteristic (size_t) const
GetSessionConfigKeys() [1/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [2/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [3/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [4/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [5/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [6/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigKeys() [7/7]
template<typename TOp , typename TKernel > std::vector< std::string > Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigKeys () const
GetSessionConfigs() [1/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
References Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault(), and Ort::detail::MakeCustomOpConfigEntryKey().
GetSessionConfigs() [2/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetSessionConfigs() [3/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetSessionConfigs() [4/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetSessionConfigs() [5/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetSessionConfigs() [6/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetSessionConfigs() [7/7]
template<typename TOp , typename TKernel > void Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs (std::unordered_map< std::string, std::string > & out, ConstSessionOptions options) const protected
GetVariadicInputHomogeneity() [1/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetVariadicInputHomogeneity() [2/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputHomogeneity() [3/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputHomogeneity() [4/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputHomogeneity() [5/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputHomogeneity() [6/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputHomogeneity() [7/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputHomogeneity () const
GetVariadicInputMinArity() [1/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetVariadicInputMinArity() [2/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicInputMinArity() [3/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicInputMinArity() [4/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicInputMinArity() [5/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicInputMinArity() [6/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicInputMinArity() [7/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicInputMinArity () const
GetVariadicOutputHomogeneity() [1/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetVariadicOutputHomogeneity() [2/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputHomogeneity() [3/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputHomogeneity() [4/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputHomogeneity() [5/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputHomogeneity() [6/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputHomogeneity() [7/7]
template<typename TOp , typename TKernel > bool Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputHomogeneity () const
GetVariadicOutputMinArity() [1/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetVariadicOutputMinArity() [2/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
GetVariadicOutputMinArity() [3/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
GetVariadicOutputMinArity() [4/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
GetVariadicOutputMinArity() [5/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
GetVariadicOutputMinArity() [6/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
GetVariadicOutputMinArity() [7/7]
template<typename TOp , typename TKernel > int Ort::CustomOpBase< TOp, TKernel >::GetVariadicOutputMinArity () const
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h