CI-FirstResponders: Ort::ThreadingOptions Struct Reference
Ort::ThreadingOptions Struct Reference
The ThreadingOptions.
#include <onnxruntime_cxx_api.h>
Public Member Functions
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions & SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
ThreadingOptions & SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
ThreadingOptions & SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
ThreadingOptions & SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
ThreadingOptions & SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
ThreadingOptions & SetGlobalCustomThreadCreationOptions (void *ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
ThreadingOptions & SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
Public Member Functions inherited from Ort::detail::Base< OrtThreadingOptions >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtThreadingOptions >
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
using contained_type = OrtThreadingOptions
Protected Attributes inherited from Ort::detail::Base< OrtThreadingOptions >
contained_type * p_
Detailed Description
The ThreadingOptions.
The ThreadingOptions used for set global threadpools' options of The Env.
Constructor & Destructor Documentation
ThreadingOptions() [1/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, and Ort::ThrowOnError().
ThreadingOptions() [2/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions() [3/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions() [4/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions() [5/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions() [6/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
ThreadingOptions() [7/7]
Ort::ThreadingOptions::ThreadingOptions ()
Wraps OrtApi::CreateThreadingOptions.
Member Function Documentation
SetGlobalCustomCreateThreadFn() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalCustomCreateThreadFn(), and Ort::ThrowOnError().
Referenced by SetGlobalCustomCreateThreadFn().
SetGlobalCustomCreateThreadFn() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomCreateThreadFn() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomCreateThreadFn() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomCreateThreadFn() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomCreateThreadFn() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomCreateThreadFn() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomCreateThreadFn (OrtCustomCreateThreadFn ort_custom_create_thread_fn)
Wraps OrtApi::SetGlobalCustomCreateThreadFn.
SetGlobalCustomJoinThreadFn() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalCustomJoinThreadFn(), and Ort::ThrowOnError().
Referenced by SetGlobalCustomJoinThreadFn().
SetGlobalCustomJoinThreadFn() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomJoinThreadFn() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomJoinThreadFn() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomJoinThreadFn() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomJoinThreadFn() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomJoinThreadFn() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomJoinThreadFn (OrtCustomJoinThreadFn ort_custom_join_thread_fn)
Wraps OrtApi::SetGlobalCustomJoinThreadFn.
SetGlobalCustomThreadCreationOptions() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalCustomThreadCreationOptions(), and Ort::ThrowOnError().
Referenced by SetGlobalCustomThreadCreationOptions().
SetGlobalCustomThreadCreationOptions() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalCustomThreadCreationOptions() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalCustomThreadCreationOptions() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalCustomThreadCreationOptions() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalCustomThreadCreationOptions() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalCustomThreadCreationOptions() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalCustomThreadCreationOptions (void * ort_custom_thread_creation_options)
Wraps OrtApi::SetGlobalCustomThreadCreationOptions.
SetGlobalDenormalAsZero() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalDenormalAsZero(), and Ort::ThrowOnError().
Referenced by SetGlobalDenormalAsZero().
SetGlobalDenormalAsZero() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalDenormalAsZero() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalDenormalAsZero() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalDenormalAsZero() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalDenormalAsZero() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalDenormalAsZero() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalDenormalAsZero ()
Wraps OrtApi::SetGlobalDenormalAsZero.
SetGlobalInterOpNumThreads() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalInterOpNumThreads(), and Ort::ThrowOnError().
Referenced by SetGlobalInterOpNumThreads().
SetGlobalInterOpNumThreads() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalInterOpNumThreads() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalInterOpNumThreads() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalInterOpNumThreads() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalInterOpNumThreads() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalInterOpNumThreads() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalInterOpNumThreads (int inter_op_num_threads)
Wraps OrtApi::SetGlobalInterOpNumThreads.
SetGlobalIntraOpNumThreads() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalIntraOpNumThreads(), and Ort::ThrowOnError().
Referenced by SetGlobalIntraOpNumThreads().
SetGlobalIntraOpNumThreads() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalIntraOpNumThreads() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalIntraOpNumThreads() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalIntraOpNumThreads() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalIntraOpNumThreads() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalIntraOpNumThreads() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalIntraOpNumThreads (int intra_op_num_threads)
Wraps OrtApi::SetGlobalIntraOpNumThreads.
SetGlobalSpinControl() [1/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
References Ort::GetApi(), Ort::detail::Base< OrtThreadingOptions >::p_, SetGlobalSpinControl(), and Ort::ThrowOnError().
Referenced by SetGlobalSpinControl().
SetGlobalSpinControl() [2/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
SetGlobalSpinControl() [3/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
SetGlobalSpinControl() [4/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
SetGlobalSpinControl() [5/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
SetGlobalSpinControl() [6/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
SetGlobalSpinControl() [7/7]
ThreadingOptions & Ort::ThreadingOptions::SetGlobalSpinControl (int allow_spinning)
Wraps OrtApi::SetGlobalSpinControl.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h