CI-FirstResponders: Ort::Session Struct Reference
Ort::Session Struct Reference
Wrapper around ::OrtSession.
#include <onnxruntime_cxx_api.h>
Public Member Functions
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Session (std::nullptr_t)
Create an empty Session object, must be assigned a valid one to be used.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options)
Wraps OrtApi::CreateSession.
Session (const Env &env, const ORTCHAR_T *model_path, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options)
Wraps OrtApi::CreateSessionFromArray.
Session (const Env &env, const void *model_data, size_t model_data_length, const SessionOptions &options, OrtPrepackedWeightsContainer *prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
ConstSession GetConst () const
UnownedSession GetUnowned () const
Public Member Functions inherited from Ort::detail::SessionImpl< OrtSession >
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
std::vector< Value > Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, size_t output_count)
Run the model returning results in an Ort allocated vector.
void Run (const RunOptions &run_options, const char *const *input_names, const Value *input_values, size_t input_count, const char *const *output_names, Value *output_values, size_t output_count)
Run the model returning results in user provided outputs Same as Run(const RunOptions&, const char* const*, const Value*, size_t,const char* const*, size_t)
void Run (const RunOptions &run_options, const IoBinding &)
Wraps OrtApi::RunWithBinding.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
AllocatedStringPtr EndProfilingAllocated (OrtAllocator *allocator)
End profiling and return a copy of the profiling file name.
Public Member Functions inherited from Ort::detail::ConstSessionImpl< T >
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
size_t GetInputCount () const
Returns the number of model inputs.
size_t GetOutputCount () const
Returns the number of model outputs.
size_t GetOverridableInitializerCount () const
Returns the number of inputs that have defaults that can be overridden.
AllocatedStringPtr GetInputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of input name at the specified index.
AllocatedStringPtr GetOutputNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of output name at then specified index.
AllocatedStringPtr GetOverridableInitializerNameAllocated (size_t index, OrtAllocator *allocator) const
Returns a copy of the overridable initializer name at then specified index.
uint64_t GetProfilingStartTimeNs () const
Wraps OrtApi::SessionGetProfilingStartTimeNs.
ModelMetadata GetModelMetadata () const
Wraps OrtApi::SessionGetModelMetadata.
TypeInfo GetInputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetInputTypeInfo.
TypeInfo GetOutputTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOutputTypeInfo.
TypeInfo GetOverridableInitializerTypeInfo (size_t index) const
Wraps OrtApi::SessionGetOverridableInitializerTypeInfo.
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::SessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = ConstSessionImpl< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
using B = Base< OrtSession >
Public Types inherited from Ort::detail::ConstSessionImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Detailed Description
Wrapper around ::OrtSession.
Constructor & Destructor Documentation
Session() [1/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [2/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
References Ort::GetApi(), Ort::detail::Base< T >::p_, and Ort::ThrowOnError().
Session() [3/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
References Ort::GetApi(), Ort::detail::Base< T >::p_, and Ort::ThrowOnError().
Session() [4/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
References Ort::GetApi(), Ort::detail::Base< T >::p_, and Ort::ThrowOnError().
Session() [5/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
References Ort::GetApi(), Ort::detail::Base< T >::p_, and Ort::ThrowOnError().
Session() [6/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [7/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [8/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [9/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [10/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Session() [11/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [12/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [13/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [14/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [15/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Session() [16/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [17/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [18/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [19/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [20/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Session() [21/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [22/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [23/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [24/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [25/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Session() [26/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [27/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [28/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [29/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [30/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Session() [31/35]
Ort::Session::Session (std::nullptr_t) explicit
Create an empty Session object, must be assigned a valid one to be used.
Session() [32/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options)
Wraps OrtApi::CreateSession.
Session() [33/35]
Ort::Session::Session (const Env & env, const ORTCHAR_T * model_path, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionWithPrepackedWeightsContainer.
Session() [34/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options)
Wraps OrtApi::CreateSessionFromArray.
Session() [35/35]
Ort::Session::Session (const Env & env, const void * model_data, size_t model_data_length, const SessionOptions & options, OrtPrepackedWeightsContainer * prepacked_weights_container)
Wraps OrtApi::CreateSessionFromArrayWithPrepackedWeightsContainer.
Member Function Documentation
GetConst() [1/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [2/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [3/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [4/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [5/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [6/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [7/7]
ConstSession Ort::Session::GetConst () const
References Ort::detail::Base< T >::p_.
GetUnowned() [1/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [2/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [3/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [4/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [5/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [6/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
GetUnowned() [7/7]
UnownedSession Ort::Session::GetUnowned () const
References Ort::detail::Base< T >::p_.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h