CI-FirstResponders: Ort::Op Struct Reference
Ort::Op Struct Reference
Create and own custom defined operation.
#include <onnxruntime_cxx_api.h>
Public Member Functions
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Op (std::nullptr_t)
Create an empty Operator object, must be assigned a valid one to be used.
Op (OrtOp *)
Take ownership of the OrtOp.
void Invoke (const OrtKernelContext *context, const Value *input_values, size_t input_count, Value *output_values, size_t output_count)
void Invoke (const OrtKernelContext *context, const OrtValue *const *input_values, size_t input_count, OrtValue *const *output_values, size_t output_count)
Public Member Functions inherited from Ort::detail::Base< OrtOp >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Static Public Member Functions
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
static Op Create (const OrtKernelInfo *info, const char *op_name, const char *domain, int version, const char **type_constraint_names, const ONNXTensorElementDataType *type_constraint_values, size_t type_constraint_count, const OpAttr *attr_values, size_t attr_count, size_t input_count, size_t output_count)
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtOp >
using contained_type = OrtOp
using contained_type = OrtOp
using contained_type = OrtOp
using contained_type = OrtOp
using contained_type = OrtOp
using contained_type = OrtOp
using contained_type = OrtOp
Protected Attributes inherited from Ort::detail::Base< OrtOp >
contained_type * p_
Detailed Description
Create and own custom defined operation.
Constructor & Destructor Documentation
Op() [1/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [2/14]
Ort::Op::Op (OrtOp * p) explicit
Take ownership of the OrtOp.
Op() [3/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [4/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Op() [5/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [6/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Op() [7/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [8/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Op() [9/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [10/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Op() [11/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [12/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Op() [13/14]
Ort::Op::Op (std::nullptr_t) explicit
Create an empty Operator object, must be assigned a valid one to be used.
Op() [14/14]
Ort::Op::Op (OrtOp *) explicit
Take ownership of the OrtOp.
Member Function Documentation
Create() [1/7]
Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
References Ort::GetApi(), and Ort::ThrowOnError().
Create() [2/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Create() [3/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Create() [4/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Create() [5/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Create() [6/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Create() [7/7]
static Op Ort::Op::Create (const OrtKernelInfo * info, const char * op_name, const char * domain, int version, const char ** type_constraint_names, const ONNXTensorElementDataType * type_constraint_values, size_t type_constraint_count, const OpAttr * attr_values, size_t attr_count, size_t input_count, size_t output_count) static
Invoke() [1/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
References Ort::GetApi(), Ort::detail::Base< OrtOp >::p_, and Ort::ThrowOnError().
Invoke() [2/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [3/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [4/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [5/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [6/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [7/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const OrtValue *const * input_values, size_t input_count, OrtValue *const * output_values, size_t output_count)
Invoke() [8/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
References Ort::GetApi(), Ort::detail::Base< OrtOp >::p_, and Ort::ThrowOnError().
Invoke() [9/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
Invoke() [10/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
Invoke() [11/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
Invoke() [12/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
Invoke() [13/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
Invoke() [14/14]
void Ort::Op::Invoke (const OrtKernelContext * context, const Value * input_values, size_t input_count, Value * output_values, size_t output_count)
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h