CI-FirstResponders: Ort::detail::AllocatorImpl< T > Struct Template Reference
Ort::detail::AllocatorImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
void * Alloc (size_t size)
MemoryAllocation GetAllocation (size_t size)
void Free (void *p)
ConstMemoryInfo GetInfo () const
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [2/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [3/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [4/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [5/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [6/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
B [7/7]
template<typename T > using Ort::detail::AllocatorImpl< T >::B = Base<T>
Member Function Documentation
Alloc() [1/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
References Ort::GetApi(), and Ort::ThrowOnError().
Alloc() [2/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Alloc() [3/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Alloc() [4/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Alloc() [5/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Alloc() [6/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Alloc() [7/7]
template<typename T > void * Ort::detail::AllocatorImpl< T >::Alloc (size_t size)
Free() [1/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
References Ort::GetApi(), and Ort::ThrowOnError().
Free() [2/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
Free() [3/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
Free() [4/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
Free() [5/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
Free() [6/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
Free() [7/7]
template<typename T > void Ort::detail::AllocatorImpl< T >::Free (void * p)
GetAllocation() [1/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
References Ort::GetApi(), and Ort::ThrowOnError().
GetAllocation() [2/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetAllocation() [3/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetAllocation() [4/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetAllocation() [5/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetAllocation() [6/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetAllocation() [7/7]
template<typename T > MemoryAllocation Ort::detail::AllocatorImpl< T >::GetAllocation (size_t size)
GetInfo() [1/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo
References Ort::GetApi(), and Ort::ThrowOnError().
GetInfo() [2/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
GetInfo() [3/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
GetInfo() [4/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
GetInfo() [5/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
GetInfo() [6/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
GetInfo() [7/7]
template<typename T > ConstMemoryInfo Ort::detail::AllocatorImpl< T >::GetInfo () const
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h