CI-FirstResponders: Ort::Status Struct Reference
Ort::Status Struct Reference
The Status that holds ownership of OrtStatus received from C API Use it to safely destroy OrtStatus* returned from the C API. Use appropriate constructors to construct an instance of a Status object from exceptions.
#include <onnxruntime_cxx_api.h>
Public Member Functions
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Status (std::nullptr_t)
Create an empty object, must be assigned a valid one to be used.
Status (OrtStatus *status)
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status (const Exception &)
Creates status instance out of exception.
Status (const std::exception &)
Creates status instance out of exception.
std::string GetErrorMessage () const
OrtErrorCode GetErrorCode () const
Public Member Functions inherited from Ort::detail::Base< OrtStatus >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtStatus >
using contained_type = OrtStatus
using contained_type = OrtStatus
using contained_type = OrtStatus
using contained_type = OrtStatus
using contained_type = OrtStatus
using contained_type = OrtStatus
using contained_type = OrtStatus
Protected Attributes inherited from Ort::detail::Base< OrtStatus >
contained_type * p_
Detailed Description
The Status that holds ownership of OrtStatus received from C API Use it to safely destroy OrtStatus* returned from the C API. Use appropriate constructors to construct an instance of a Status object from exceptions.
Constructor & Destructor Documentation
Status() [1/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [2/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [3/28]
Ort::Status::Status (const Exception & e) explicit
Creates status instance out of exception.
References OrtApi::CreateStatus(), Ort::GetApi(), Ort::Exception::GetOrtErrorCode(), Ort::detail::Base< OrtStatus >::p_, and Ort::Exception::what().
Status() [4/28]
Ort::Status::Status (const std::exception & e) explicit
Creates status instance out of exception.
References OrtApi::CreateStatus(), Ort::GetApi(), ORT_FAIL, and Ort::detail::Base< OrtStatus >::p_.
Status() [5/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [6/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [7/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [8/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Status() [9/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [10/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [11/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [12/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Status() [13/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [14/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [15/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [16/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Status() [17/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [18/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [19/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [20/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Status() [21/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [22/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [23/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [24/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Status() [25/28]
Ort::Status::Status (std::nullptr_t) explicit
Create an empty object, must be assigned a valid one to be used.
Status() [26/28]
Ort::Status::Status (OrtStatus * status) explicit
Takes ownership of OrtStatus instance returned from the C API. Must be non-null.
Status() [27/28]
Ort::Status::Status (const Exception &) explicit
Creates status instance out of exception.
Status() [28/28]
Ort::Status::Status (const std::exception &) explicit
Creates status instance out of exception.
Member Function Documentation
GetErrorCode() [1/7]
OrtErrorCode Ort::Status::GetErrorCode () const
References Ort::GetApi(), and Ort::detail::Base< OrtStatus >::p_.
Referenced by Ort::detail::ThrowStatus().
GetErrorCode() [2/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorCode() [3/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorCode() [4/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorCode() [5/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorCode() [6/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorCode() [7/7]
OrtErrorCode Ort::Status::GetErrorCode () const
GetErrorMessage() [1/7]
std::string Ort::Status::GetErrorMessage () const
References Ort::GetApi(), GetErrorMessage(), and Ort::detail::Base< OrtStatus >::p_.
Referenced by GetErrorMessage(), and Ort::detail::ThrowStatus().
GetErrorMessage() [2/7]
std::string Ort::Status::GetErrorMessage () const
GetErrorMessage() [3/7]
std::string Ort::Status::GetErrorMessage () const
GetErrorMessage() [4/7]
std::string Ort::Status::GetErrorMessage () const
GetErrorMessage() [5/7]
std::string Ort::Status::GetErrorMessage () const
GetErrorMessage() [6/7]
std::string Ort::Status::GetErrorMessage () const
GetErrorMessage() [7/7]
std::string Ort::Status::GetErrorMessage () const
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h