CI-FirstResponders: Ort::detail::TypeInfoImpl< T > Struct Template Reference
Ort::detail::TypeInfoImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
ConstTensorTypeAndShapeInfo GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
ConstSequenceTypeInfo GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
ConstMapTypeInfo GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
ONNXType GetONNXType () const
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [2/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [3/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [4/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [5/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [6/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
B [7/7]
template<typename T > using Ort::detail::TypeInfoImpl< T >::B = Base<T>
Member Function Documentation
GetMapTypeInfo() [1/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
References Ort::GetApi(), and Ort::ThrowOnError().
GetMapTypeInfo() [2/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetMapTypeInfo() [3/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetMapTypeInfo() [4/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetMapTypeInfo() [5/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetMapTypeInfo() [6/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetMapTypeInfo() [7/7]
template<typename T > ConstMapTypeInfo Ort::detail::TypeInfoImpl< T >::GetMapTypeInfo () const
Wraps OrtApi::CastTypeInfoToMapTypeInfo.
GetONNXType() [1/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType
References Ort::GetApi(), and Ort::ThrowOnError().
GetONNXType() [2/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetONNXType() [3/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetONNXType() [4/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetONNXType() [5/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetONNXType() [6/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetONNXType() [7/7]
template<typename T > ONNXType Ort::detail::TypeInfoImpl< T >::GetONNXType () const
GetSequenceTypeInfo() [1/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
References Ort::GetApi(), and Ort::ThrowOnError().
GetSequenceTypeInfo() [2/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetSequenceTypeInfo() [3/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetSequenceTypeInfo() [4/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetSequenceTypeInfo() [5/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetSequenceTypeInfo() [6/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetSequenceTypeInfo() [7/7]
template<typename T > ConstSequenceTypeInfo Ort::detail::TypeInfoImpl< T >::GetSequenceTypeInfo () const
Wraps OrtApi::CastTypeInfoToSequenceTypeInfo.
GetTensorTypeAndShapeInfo() [1/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo
Wraps OrtApi::CastTypeInfoToTensorInfo.
References Ort::GetApi(), and Ort::ThrowOnError().
GetTensorTypeAndShapeInfo() [2/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
GetTensorTypeAndShapeInfo() [3/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
GetTensorTypeAndShapeInfo() [4/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
GetTensorTypeAndShapeInfo() [5/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
GetTensorTypeAndShapeInfo() [6/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
GetTensorTypeAndShapeInfo() [7/7]
template<typename T > ConstTensorTypeAndShapeInfo Ort::detail::TypeInfoImpl< T >::GetTensorTypeAndShapeInfo () const
Wraps OrtApi::CastTypeInfoToTensorInfo.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h