CI-FirstResponders: Ort::detail::IoBindingImpl< T > Struct Template Reference
Ort::detail::IoBindingImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = ConstIoBindingImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::ConstIoBindingImpl< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
void BindInput (const char *name, const Value &)
void BindOutput (const char *name, const Value &)
void BindOutput (const char *name, const OrtMemoryInfo *)
void ClearBoundInputs ()
void ClearBoundOutputs ()
void SynchronizeInputs ()
void SynchronizeOutputs ()
Public Member Functions inherited from Ort::detail::ConstIoBindingImpl< T >
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
std::vector< std::string > GetOutputNames () const
std::vector< std::string > GetOutputNames (OrtAllocator *) const
std::vector< Value > GetOutputValues () const
std::vector< Value > GetOutputValues (OrtAllocator *) const
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [2/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [3/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [4/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [5/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [6/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [7/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [8/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [9/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [10/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [11/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [12/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [13/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [14/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [15/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [16/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [17/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [18/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [19/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [20/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [21/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [22/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [23/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [24/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [25/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [26/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [27/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [28/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [29/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [30/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [31/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [32/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [33/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [34/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [35/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [36/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [37/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [38/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [39/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [40/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [41/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [42/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [43/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [44/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [45/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [46/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [47/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [48/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [49/56]
template<typename T > using Ort::detail::IoBindingImpl< T >::B = ConstIoBindingImpl<T>
B [50/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [51/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [52/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [53/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [54/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [55/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
B [56/56]
template<typename T > using Ort::detail::ConstIoBindingImpl< T >::B = Base<T>
Member Function Documentation
BindInput() [1/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value & value)
References Ort::GetApi(), and Ort::ThrowOnError().
BindInput() [2/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindInput() [3/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindInput() [4/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindInput() [5/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindInput() [6/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindInput() [7/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindInput (const char * name, const Value &)
BindOutput() [1/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo * mem_info)
References Ort::GetApi(), and Ort::ThrowOnError().
BindOutput() [2/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [3/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [4/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [5/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [6/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [7/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const OrtMemoryInfo *)
BindOutput() [8/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value & value)
References Ort::GetApi(), and Ort::ThrowOnError().
BindOutput() [9/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
BindOutput() [10/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
BindOutput() [11/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
BindOutput() [12/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
BindOutput() [13/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
BindOutput() [14/14]
template<typename T > void Ort::detail::IoBindingImpl< T >::BindOutput (const char * name, const Value &)
ClearBoundInputs() [1/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs
References Ort::GetApi().
ClearBoundInputs() [2/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundInputs() [3/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundInputs() [4/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundInputs() [5/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundInputs() [6/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundInputs() [7/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundInputs ()
ClearBoundOutputs() [1/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs
References Ort::GetApi().
ClearBoundOutputs() [2/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
ClearBoundOutputs() [3/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
ClearBoundOutputs() [4/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
ClearBoundOutputs() [5/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
ClearBoundOutputs() [6/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
ClearBoundOutputs() [7/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::ClearBoundOutputs ()
SynchronizeInputs() [1/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs
References Ort::GetApi(), and Ort::ThrowOnError().
SynchronizeInputs() [2/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeInputs() [3/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeInputs() [4/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeInputs() [5/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeInputs() [6/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeInputs() [7/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeInputs ()
SynchronizeOutputs() [1/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs
References Ort::GetApi(), and Ort::ThrowOnError().
SynchronizeOutputs() [2/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
SynchronizeOutputs() [3/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
SynchronizeOutputs() [4/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
SynchronizeOutputs() [5/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
SynchronizeOutputs() [6/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
SynchronizeOutputs() [7/7]
template<typename T > void Ort::detail::IoBindingImpl< T >::SynchronizeOutputs ()
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h