CI-FirstResponders: Ort::CustomOpApi Struct Reference
Ort::CustomOpApi Struct Reference
This entire structure is deprecated, but we not marking it as a whole yet since we want to preserve for the next release.
#include <onnxruntime_cxx_api.h>
Public Member Functions
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
CustomOpApi (const OrtApi &api)
OrtTensorTypeAndShapeInfo * GetTensorTypeAndShape (_In_ const OrtValue *value)
size_t GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo *info)
ONNXTensorElementDataType GetTensorElementType (const OrtTensorTypeAndShapeInfo *info)
size_t GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo *info)
void GetDimensions (_In_ const OrtTensorTypeAndShapeInfo *info, _Out_ int64_t *dim_values, size_t dim_values_length)
void SetDimensions (OrtTensorTypeAndShapeInfo *info, _In_ const int64_t *dim_values, size_t dim_count)
template<typename T >
T * GetTensorMutableData (_Inout_ OrtValue *value)
template<typename T >
const T * GetTensorData (_Inout_ const OrtValue *value)
const OrtMemoryInfo * GetTensorMemoryInfo (_In_ const OrtValue *value)
std::vector< int64_t > GetTensorShape (const OrtTensorTypeAndShapeInfo *info)
void ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo *input)
size_t KernelContext_GetInputCount (const OrtKernelContext *context)
const OrtValue * KernelContext_GetInput (const OrtKernelContext *context, _In_ size_t index)
size_t KernelContext_GetOutputCount (const OrtKernelContext *context)
OrtValue * KernelContext_GetOutput (OrtKernelContext *context, _In_ size_t index, _In_ const int64_t *dim_values, size_t dim_count)
void * KernelContext_GetGPUComputeStream (const OrtKernelContext *context)
void ThrowOnError (OrtStatus *result)
OrtOpAttr * CreateOpAttr (_In_ const char *name, _In_ const void *data, _In_ int len, _In_ OrtOpAttrType type)
void ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr *op_attr)
OrtOp * CreateOp (_In_ const OrtKernelInfo *info, _In_ const char *op_name, _In_ const char *domain, _In_ int version, _In_opt_ const char **type_constraint_names, _In_opt_ const ONNXTensorElementDataType *type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const *attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
void InvokeOp (_In_ const OrtKernelContext *context, _In_ const OrtOp *ort_op, _In_ const OrtValue *const *input_values, _In_ int input_count, _Inout_ OrtValue *const *output_values, _In_ int output_count)
void ReleaseOp (_Frees_ptr_opt_ OrtOp *ort_op)
template<typename T >
T KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
OrtKernelInfo * CopyKernelInfo (_In_ const OrtKernelInfo *info)
void ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo *info_copy)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
float KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
template<>
int64_t KernelInfoGetAttribute (_In_ const OrtKernelInfo *info, _In_ const char *name)
Detailed Description
This entire structure is deprecated, but we not marking it as a whole yet since we want to preserve for the next release.
Constructor & Destructor Documentation
CustomOpApi() [1/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [2/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [3/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [4/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [5/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [6/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
CustomOpApi() [7/7]
Ort::CustomOpApi::CustomOpApi (const OrtApi & api)
Member Function Documentation
CopyKernelInfo() [1/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
References Ort::ThrowOnError().
CopyKernelInfo() [2/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CopyKernelInfo() [3/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CopyKernelInfo() [4/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CopyKernelInfo() [5/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CopyKernelInfo() [6/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CopyKernelInfo() [7/7]
OrtKernelInfo * Ort::CustomOpApi::CopyKernelInfo (_In_ const OrtKernelInfo * info)
Deprecated:
use Ort::KernelInfo::Copy querying attributes [[deprecated]] This interface is not exception safe
CreateOp() [1/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
References Ort::ThrowOnError().
CreateOp() [2/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOp() [3/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOp() [4/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOp() [5/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOp() [6/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOp() [7/7]
OrtOp * Ort::CustomOpApi::CreateOp (_In_ const OrtKernelInfo * info, _In_ const char * op_name, _In_ const char * domain, _In_ int version, _In_opt_ const char ** type_constraint_names, _In_opt_ const ONNXTensorElementDataType * type_constraint_values, _In_opt_ int type_constraint_count, _In_opt_ const OrtOpAttr *const * attr_values, _In_opt_ int attr_count, _In_ int input_count, _In_ int output_count)
Deprecated:
use Ort::Op [[deprecated]] This interface is not exception safe.
CreateOpAttr() [1/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
References Ort::ThrowOnError().
CreateOpAttr() [2/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
CreateOpAttr() [3/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
CreateOpAttr() [4/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
CreateOpAttr() [5/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
CreateOpAttr() [6/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
CreateOpAttr() [7/7]
OrtOpAttr * Ort::CustomOpApi::CreateOpAttr (_In_ const char * name, _In_ const void * data, _In_ int len, _In_ OrtOpAttrType type)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
GetDimensions() [1/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetDimensions() [2/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensions() [3/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensions() [4/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensions() [5/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensions() [6/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensions() [7/7]
void Ort::CustomOpApi::GetDimensions (_In_ const OrtTensorTypeAndShapeInfo * info, _Out_ int64_t * dim_values, size_t dim_values_length)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetDimensionsCount() [1/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetDimensionsCount() [2/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetDimensionsCount() [3/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetDimensionsCount() [4/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetDimensionsCount() [5/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetDimensionsCount() [6/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetDimensionsCount() [7/7]
size_t Ort::CustomOpApi::GetDimensionsCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetDimensionsCount() [[deprecated]] This interface is redundant.
GetTensorData() [1/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorData() [2/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorData() [3/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorData() [4/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorData() [5/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorData() [6/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorData() [7/7]
template<typename T > const T * Ort::CustomOpApi::GetTensorData (_Inout_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorData() [[deprecated]] This interface is redundant.
GetTensorElementType() [1/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorElementType() [2/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorElementType() [3/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorElementType() [4/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorElementType() [5/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorElementType() [6/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorElementType() [7/7]
ONNXTensorElementDataType Ort::CustomOpApi::GetTensorElementType (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementType() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [1/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorMemoryInfo() [2/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [3/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [4/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [5/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [6/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMemoryInfo() [7/7]
const OrtMemoryInfo * Ort::CustomOpApi::GetTensorMemoryInfo (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMemoryInfo() [[deprecated]] This interface is redundant.
GetTensorMutableData() [1/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorMutableData() [2/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorMutableData() [3/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorMutableData() [4/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorMutableData() [5/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorMutableData() [6/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorMutableData() [7/7]
template<typename T > T * Ort::CustomOpApi::GetTensorMutableData (_Inout_ OrtValue * value)
Deprecated:
use Ort::Value::GetTensorMutableData() [[deprecated]] This interface is redundant.
GetTensorShape() [1/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorShape() [2/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShape() [3/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShape() [4/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShape() [5/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShape() [6/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShape() [7/7]
std::vector< int64_t > Ort::CustomOpApi::GetTensorShape (const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetShape() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [1/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
GetTensorShapeElementCount() [2/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [3/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [4/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [5/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [6/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorShapeElementCount() [7/7]
size_t Ort::CustomOpApi::GetTensorShapeElementCount (_In_ const OrtTensorTypeAndShapeInfo * info)
Deprecated:
use Ort::TensorTypeAndShapeInfo::GetElementCount() [[deprecated]] This interface is redundant.
GetTensorTypeAndShape() [1/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
References Ort::ThrowOnError().
GetTensorTypeAndShape() [2/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
GetTensorTypeAndShape() [3/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
GetTensorTypeAndShape() [4/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
GetTensorTypeAndShape() [5/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
GetTensorTypeAndShape() [6/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
GetTensorTypeAndShape() [7/7]
OrtTensorTypeAndShapeInfo * Ort::CustomOpApi::GetTensorTypeAndShape (_In_ const OrtValue * value)
Deprecated:
use Ort::Value::GetTensorTypeAndShape() [[deprecated]] This interface produces a pointer that must be released. Not exception safe.
InvokeOp() [1/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
References Ort::ThrowOnError().
InvokeOp() [2/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
InvokeOp() [3/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
InvokeOp() [4/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
InvokeOp() [5/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
InvokeOp() [6/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
InvokeOp() [7/7]
void Ort::CustomOpApi::InvokeOp (_In_ const OrtKernelContext * context, _In_ const OrtOp * ort_op, _In_ const OrtValue *const * input_values, _In_ int input_count, _Inout_ OrtValue *const * output_values, _In_ int output_count)
Deprecated:
use Ort::Op::Invoke [[deprecated]] This interface is redundant
KernelContext_GetGPUComputeStream() [1/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
KernelContext_GetGPUComputeStream() [2/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetGPUComputeStream() [3/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetGPUComputeStream() [4/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetGPUComputeStream() [5/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetGPUComputeStream() [6/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetGPUComputeStream() [7/7]
void * Ort::CustomOpApi::KernelContext_GetGPUComputeStream (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetGPUComputeStream [[deprecated]] This interface is redundant.
KernelContext_GetInput() [1/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
KernelContext_GetInput() [2/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInput() [3/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInput() [4/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInput() [5/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInput() [6/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInput() [7/7]
const OrtValue * Ort::CustomOpApi::KernelContext_GetInput (const OrtKernelContext * context, _In_ size_t index)
Deprecated:
use Ort::KernelContext::GetInput [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [1/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
KernelContext_GetInputCount() [2/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [3/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [4/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [5/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [6/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetInputCount() [7/7]
size_t Ort::CustomOpApi::KernelContext_GetInputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetInputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [1/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
KernelContext_GetOutput() [2/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [3/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [4/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [5/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [6/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutput() [7/7]
OrtValue * Ort::CustomOpApi::KernelContext_GetOutput (OrtKernelContext * context, _In_ size_t index, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
use Ort::KernelContext::GetOutput [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [1/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
KernelContext_GetOutputCount() [2/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [3/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [4/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [5/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [6/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelContext_GetOutputCount() [7/7]
size_t Ort::CustomOpApi::KernelContext_GetOutputCount (const OrtKernelContext * context)
Deprecated:
use Ort::KernelContext::GetOutputCount [[deprecated]] This interface is redundant.
KernelInfoGetAttribute() [1/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [2/21]
template<> std::vector< int64_t > Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [3/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [4/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [5/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [6/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [7/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [8/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [9/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [10/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [11/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [12/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [13/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [14/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [15/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [16/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [17/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [18/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [19/21]
template<typename T > T Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
Deprecated:
use Ort::KernelInfo for automatic lifespan management or for querying attributes [[deprecated]] This interface is redundant
KernelInfoGetAttribute() [20/21]
template<> float Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
KernelInfoGetAttribute() [21/21]
template<> int64_t Ort::CustomOpApi::KernelInfoGetAttribute (_In_ const OrtKernelInfo * info, _In_ const char * name)
References Ort::ThrowOnError().
ReleaseKernelInfo() [1/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [2/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [3/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [4/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [5/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [6/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseKernelInfo() [7/7]
void Ort::CustomOpApi::ReleaseKernelInfo (_Frees_ptr_opt_ OrtKernelInfo * info_copy)
Deprecated:
use Ort::KernelInfo for lifespan management querying attributes [[deprecated]] This interface is not exception safe
ReleaseOp() [1/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [2/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [3/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [4/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [5/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [6/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOp() [7/7]
void Ort::CustomOpApi::ReleaseOp (_Frees_ptr_opt_ OrtOp * ort_op)
Deprecated:
use Ort::Op for automatic lifespan management. [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [1/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [2/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [3/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [4/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [5/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [6/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseOpAttr() [7/7]
void Ort::CustomOpApi::ReleaseOpAttr (_Frees_ptr_opt_ OrtOpAttr * op_attr)
Deprecated:
use Ort::OpAttr [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [1/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [2/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [3/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [4/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [5/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [6/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
ReleaseTensorTypeAndShapeInfo() [7/7]
void Ort::CustomOpApi::ReleaseTensorTypeAndShapeInfo (OrtTensorTypeAndShapeInfo * input)
Deprecated:
use TensorTypeAndShapeInfo instances for automatic ownership. [[deprecated]] This interface is not exception safe.
SetDimensions() [1/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
References Ort::ThrowOnError().
SetDimensions() [2/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
SetDimensions() [3/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
SetDimensions() [4/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
SetDimensions() [5/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
SetDimensions() [6/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
SetDimensions() [7/7]
void Ort::CustomOpApi::SetDimensions (OrtTensorTypeAndShapeInfo * info, _In_ const int64_t * dim_values, size_t dim_count)
Deprecated:
[[deprecated]] This interface sets dimensions to TensorTypeAndShapeInfo, but has no effect on the OrtValue.
ThrowOnError() [1/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
References Ort::ThrowOnError().
ThrowOnError() [2/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
ThrowOnError() [3/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
ThrowOnError() [4/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
ThrowOnError() [5/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
ThrowOnError() [6/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
ThrowOnError() [7/7]
void Ort::CustomOpApi::ThrowOnError (OrtStatus * result)
Deprecated:
use Ort::ThrowOnError() [[deprecated]] This interface is redundant.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h