CI-FirstResponders: Ort::RunOptions Struct Reference
Ort::RunOptions Struct Reference
RunOptions.
#include <onnxruntime_cxx_api.h>
Public Member Functions
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
RunOptions (std::nullptr_t)
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions & SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
int GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
RunOptions & SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
int GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
RunOptions & SetRunTag (const char *run_tag)
wraps OrtApi::RunOptionsSetRunTag
const char * GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
RunOptions & AddConfigEntry (const char *config_key, const char *config_value)
Wraps OrtApi::AddRunConfigEntry.
RunOptions & SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
RunOptions & UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Public Member Functions inherited from Ort::detail::Base< OrtRunOptions >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtRunOptions >
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
using contained_type = OrtRunOptions
Protected Attributes inherited from Ort::detail::Base< OrtRunOptions >
contained_type * p_
Detailed Description
RunOptions.
Constructor & Destructor Documentation
RunOptions() [1/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [2/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
RunOptions() [3/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [4/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions() [5/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [6/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions() [7/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [8/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions() [9/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [10/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions() [11/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [12/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
RunOptions() [13/14]
Ort::RunOptions::RunOptions (std::nullptr_t) explicit
Create an empty RunOptions object, must be assigned a valid one to be used.
RunOptions() [14/14]
Ort::RunOptions::RunOptions ()
Wraps OrtApi::CreateRunOptions.
Member Function Documentation
AddConfigEntry() [1/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
AddConfigEntry() [2/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
AddConfigEntry() [3/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
AddConfigEntry() [4/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
AddConfigEntry() [5/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
AddConfigEntry() [6/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
AddConfigEntry() [7/7]
RunOptions & Ort::RunOptions::AddConfigEntry (const char * config_key, const char * config_value)
Wraps OrtApi::AddRunConfigEntry.
GetRunLogSeverityLevel() [1/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
GetRunLogSeverityLevel() [2/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogSeverityLevel() [3/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogSeverityLevel() [4/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogSeverityLevel() [5/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogSeverityLevel() [6/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogSeverityLevel() [7/7]
int Ort::RunOptions::GetRunLogSeverityLevel () const
Wraps OrtApi::RunOptionsGetRunLogSeverityLevel.
GetRunLogVerbosityLevel() [1/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
GetRunLogVerbosityLevel() [2/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunLogVerbosityLevel() [3/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunLogVerbosityLevel() [4/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunLogVerbosityLevel() [5/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunLogVerbosityLevel() [6/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunLogVerbosityLevel() [7/7]
int Ort::RunOptions::GetRunLogVerbosityLevel () const
Wraps OrtApi::RunOptionsGetRunLogVerbosityLevel.
GetRunTag() [1/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
GetRunTag() [2/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
GetRunTag() [3/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
GetRunTag() [4/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
GetRunTag() [5/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
GetRunTag() [6/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
GetRunTag() [7/7]
const char * Ort::RunOptions::GetRunTag () const
Wraps OrtApi::RunOptionsGetRunTag.
SetRunLogSeverityLevel() [1/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int level)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
SetRunLogSeverityLevel() [2/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogSeverityLevel() [3/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogSeverityLevel() [4/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogSeverityLevel() [5/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogSeverityLevel() [6/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogSeverityLevel() [7/7]
RunOptions & Ort::RunOptions::SetRunLogSeverityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogSeverityLevel.
SetRunLogVerbosityLevel() [1/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int level)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
SetRunLogVerbosityLevel() [2/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunLogVerbosityLevel() [3/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunLogVerbosityLevel() [4/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunLogVerbosityLevel() [5/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunLogVerbosityLevel() [6/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunLogVerbosityLevel() [7/7]
RunOptions & Ort::RunOptions::SetRunLogVerbosityLevel (int)
Wraps OrtApi::RunOptionsSetRunLogVerbosityLevel.
SetRunTag() [1/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
SetRunTag() [2/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetRunTag() [3/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetRunTag() [4/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetRunTag() [5/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetRunTag() [6/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetRunTag() [7/7]
RunOptions & Ort::RunOptions::SetRunTag (const char * run_tag)
wraps OrtApi::RunOptionsSetRunTag
SetTerminate() [1/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
SetTerminate() [2/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
SetTerminate() [3/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
SetTerminate() [4/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
SetTerminate() [5/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
SetTerminate() [6/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
SetTerminate() [7/7]
RunOptions & Ort::RunOptions::SetTerminate ()
Terminates all currently executing Session::Run calls that were made using this RunOptions instance.
If a currently executing session needs to be force terminated, this can be called from another thread to force it to fail with an error Wraps OrtApi::RunOptionsSetTerminate
UnsetTerminate() [1/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
References Ort::GetApi(), Ort::detail::Base< OrtRunOptions >::p_, and Ort::ThrowOnError().
UnsetTerminate() [2/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
UnsetTerminate() [3/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
UnsetTerminate() [4/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
UnsetTerminate() [5/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
UnsetTerminate() [6/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
UnsetTerminate() [7/7]
RunOptions & Ort::RunOptions::UnsetTerminate ()
Clears the terminate flag so this RunOptions instance can be used in a new Session::Run call without it instantly terminating.
Wraps OrtApi::RunOptionsUnsetTerminate
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h