CI-FirstResponders: Ort::detail::ConstSessionOptionsImpl< T > Struct Template Reference
Ort::detail::ConstSessionOptionsImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
SessionOptions Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
std::string GetConfigEntry (const char *config_key) const
Wraps OrtApi::GetSessionConfigEntry.
bool HasConfigEntry (const char *config_key) const
Wraps OrtApi::HasSessionConfigEntry.
std::string GetConfigEntryOrDefault (const char *config_key, const std::string &def)
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [2/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [3/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [4/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [5/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [6/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
B [7/7]
template<typename T > using Ort::detail::ConstSessionOptionsImpl< T >::B = Base<T>
Member Function Documentation
Clone() [1/7]
template<typename T > Ort::SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [2/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [3/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [4/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [5/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [6/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
Clone() [7/7]
template<typename T > SessionOptions Ort::detail::ConstSessionOptionsImpl< T >::Clone () const
Creates and returns a copy of this SessionOptions object. Wraps OrtApi::CloneSessionOptions.
GetConfigEntry() [1/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
References Ort::GetApi(), and Ort::ThrowOnError().
GetConfigEntry() [2/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntry() [3/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntry() [4/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntry() [5/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntry() [6/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntry() [7/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntry (const char * config_key) const
Wraps OrtApi::GetSessionConfigEntry.
GetConfigEntryOrDefault() [1/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
Referenced by Ort::CustomOpBase< TOp, TKernel >::GetSessionConfigs().
GetConfigEntryOrDefault() [2/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
GetConfigEntryOrDefault() [3/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
GetConfigEntryOrDefault() [4/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
GetConfigEntryOrDefault() [5/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
GetConfigEntryOrDefault() [6/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
GetConfigEntryOrDefault() [7/7]
template<typename T > std::string Ort::detail::ConstSessionOptionsImpl< T >::GetConfigEntryOrDefault (const char * config_key, const std::string & def)
HasConfigEntry() [1/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [2/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [3/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [4/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [5/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [6/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
HasConfigEntry() [7/7]
template<typename T > bool Ort::detail::ConstSessionOptionsImpl< T >::HasConfigEntry (const char * config_key) const
Wraps OrtApi::HasSessionConfigEntry.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h