CI-FirstResponders: OrtCustomOp Struct Reference
OrtCustomOp Struct Reference
Global
#include <onnxruntime_c_api.h>
Public Member Functions
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
void *ORT_API_CALL * CreateKernel (_In_ const struct OrtCustomOp *op, _In_ const OrtApi *api, _In_ const OrtKernelInfo *info)
const char *ORT_API_CALL * GetName (_In_ const struct OrtCustomOp *op)
const char *ORT_API_CALL * GetExecutionProviderType (_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetInputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetInputTypeCount)(_In_ const struct OrtCustomOp *op)
ONNXTensorElementDataType (ORT_API_CALL *GetOutputType)(_In_ const struct OrtCustomOp *op
size_t (ORT_API_CALL *GetOutputTypeCount)(_In_ const struct OrtCustomOp *op)
void (ORT_API_CALL *KernelCompute)(_In_ void *op_kernel
void (ORT_API_CALL *KernelDestroy)(_In_ void *op_kernel)
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetInputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtCustomOpInputOutputCharacteristic (ORT_API_CALL *GetOutputCharacteristic)(_In_ const struct OrtCustomOp *op
OrtMemType (ORT_API_CALL *GetInputMemoryType)(_In_ const struct OrtCustomOp *op
int (ORT_API_CALL *GetVariadicInputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicInputHomogeneity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputMinArity)(_In_ const struct OrtCustomOp *op)
int (ORT_API_CALL *GetVariadicOutputHomogeneity)(_In_ const struct OrtCustomOp *op)
Public Attributes
uint32_t version
_In_ size_t index
_In_ OrtKernelContext * context
Member Function Documentation
CreateKernel() [1/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
CreateKernel() [2/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
CreateKernel() [3/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
CreateKernel() [4/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
CreateKernel() [5/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
CreateKernel() [6/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
CreateKernel() [7/7]
void *ORT_API_CALL * OrtCustomOp::CreateKernel (_In_ const struct OrtCustomOp * op, _In_ const OrtApi * api, _In_ const OrtKernelInfo * info)
GetExecutionProviderType() [1/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetExecutionProviderType() [2/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetExecutionProviderType() [3/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetExecutionProviderType() [4/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetExecutionProviderType() [5/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetExecutionProviderType() [6/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetExecutionProviderType() [7/7]
const char *ORT_API_CALL * OrtCustomOp::GetExecutionProviderType (_In_ const struct OrtCustomOp * op)
GetName() [1/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
GetName() [2/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
GetName() [3/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
GetName() [4/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
GetName() [5/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
GetName() [6/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
GetName() [7/7]
const char *ORT_API_CALL * OrtCustomOp::GetName (_In_ const struct OrtCustomOp * op)
int() [1/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [2/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [3/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [4/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [5/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [6/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [7/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputHomogeneity) const
int() [8/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [9/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [10/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [11/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [12/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [13/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [14/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicInputMinArity) const
int() [15/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [16/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [17/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [18/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [19/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [20/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [21/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputHomogeneity) const
int() [22/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [23/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [24/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [25/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [26/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [27/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
int() [28/28]
OrtCustomOp::int (ORT_API_CALL * GetVariadicOutputMinArity) const
ONNXTensorElementDataType() [1/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [2/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [3/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [4/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [5/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [6/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [7/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetInputType) const
ONNXTensorElementDataType() [8/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [9/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [10/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [11/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [12/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [13/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
ONNXTensorElementDataType() [14/14]
OrtCustomOp::ONNXTensorElementDataType (ORT_API_CALL * GetOutputType) const
OrtCustomOpInputOutputCharacteristic() [1/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [2/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [3/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [4/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [5/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [6/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [7/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetInputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [8/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [9/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [10/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [11/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [12/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [13/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtCustomOpInputOutputCharacteristic() [14/14]
OrtCustomOp::OrtCustomOpInputOutputCharacteristic (ORT_API_CALL * GetOutputCharacteristic) const
OrtMemType() [1/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [2/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [3/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [4/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [5/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [6/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
OrtMemType() [7/7]
OrtCustomOp::OrtMemType (ORT_API_CALL * GetInputMemoryType) const
size_t() [1/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [2/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [3/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [4/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [5/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [6/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [7/14]
OrtCustomOp::size_t (ORT_API_CALL * GetInputTypeCount) const
size_t() [8/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [9/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [10/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [11/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [12/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [13/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
size_t() [14/14]
OrtCustomOp::size_t (ORT_API_CALL * GetOutputTypeCount) const
void() [1/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [2/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [3/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [4/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [5/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [6/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [7/14]
OrtCustomOp::void (ORT_API_CALL * KernelCompute)
void() [8/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [9/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [10/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [11/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [12/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [13/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
void() [14/14]
OrtCustomOp::void (ORT_API_CALL * KernelDestroy)
Member Data Documentation
context
_In_ OrtKernelContext * OrtCustomOp::context
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
index
_In_ size_t OrtCustomOp::index
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
version
uint32_t OrtCustomOp::version
Referenced by Ort::CustomOpBase< TOp, TKernel >::CustomOpBase().
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_c_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_c_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_c_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_c_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_c_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_c_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_c_api.h