CI-FirstResponders: Ort::MemoryInfo Struct Reference
Ort::MemoryInfo Struct Reference
Wrapper around ::OrtMemoryInfo.
#include <onnxruntime_cxx_api.h>
Public Member Functions
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
MemoryInfo (std::nullptr_t)
No instance is created.
MemoryInfo (OrtMemoryInfo *p)
Take ownership of a pointer created by C Api.
MemoryInfo (const char *name, OrtAllocatorType type, int id, OrtMemType mem_type)
ConstMemoryInfo GetConst () const
Public Member Functions inherited from Ort::detail::MemoryInfoImpl< OrtMemoryInfo >
std::string GetAllocatorName () const
std::string GetAllocatorName () const
std::string GetAllocatorName () const
std::string GetAllocatorName () const
std::string GetAllocatorName () const
std::string GetAllocatorName () const
std::string GetAllocatorName () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
OrtAllocatorType GetAllocatorType () const
int GetDeviceId () const
int GetDeviceId () const
int GetDeviceId () const
int GetDeviceId () const
int GetDeviceId () const
int GetDeviceId () const
int GetDeviceId () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemoryInfoDeviceType GetDeviceType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
OrtMemType GetMemoryType () const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
bool operator== (const MemoryInfoImpl< U > &o) const
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Static Public Member Functions
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
static MemoryInfo CreateCpu (OrtAllocatorType type, OrtMemType mem_type1)
Additional Inherited Members
Public Types inherited from Ort::detail::MemoryInfoImpl< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
using B = Base< OrtMemoryInfo >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Detailed Description
Wrapper around ::OrtMemoryInfo.
Constructor & Destructor Documentation
MemoryInfo() [1/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [2/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [3/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
References Ort::GetApi(), Ort::detail::Base< T >::p_, and Ort::ThrowOnError().
MemoryInfo() [4/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [5/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [6/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
MemoryInfo() [7/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [8/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [9/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
MemoryInfo() [10/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [11/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [12/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
MemoryInfo() [13/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [14/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [15/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
MemoryInfo() [16/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [17/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [18/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
MemoryInfo() [19/21]
Ort::MemoryInfo::MemoryInfo (std::nullptr_t) explicit
No instance is created.
MemoryInfo() [20/21]
Ort::MemoryInfo::MemoryInfo (OrtMemoryInfo * p) explicit
Take ownership of a pointer created by C Api.
MemoryInfo() [21/21]
Ort::MemoryInfo::MemoryInfo (const char * name, OrtAllocatorType type, int id, OrtMemType mem_type)
Member Function Documentation
CreateCpu() [1/7]
MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
References Ort::GetApi(), and Ort::ThrowOnError().
CreateCpu() [2/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
CreateCpu() [3/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
CreateCpu() [4/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
CreateCpu() [5/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
CreateCpu() [6/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
CreateCpu() [7/7]
static MemoryInfo Ort::MemoryInfo::CreateCpu (OrtAllocatorType type, OrtMemType mem_type1) static
GetConst() [1/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [2/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [3/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [4/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [5/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [6/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
GetConst() [7/7]
ConstMemoryInfo Ort::MemoryInfo::GetConst () const
References Ort::detail::Base< T >::p_.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h