CI-FirstResponders: Ort::ModelMetadata Struct Reference
Ort::ModelMetadata Struct Reference
Wrapper around ::OrtModelMetadata.
#include <onnxruntime_cxx_api.h>
Public Member Functions
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
ModelMetadata (std::nullptr_t)
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata (OrtModelMetadata *p)
Used for interop with the C API.
AllocatedStringPtr GetProducerNameAllocated (OrtAllocator *allocator) const
Returns a copy of the producer name.
AllocatedStringPtr GetGraphNameAllocated (OrtAllocator *allocator) const
Returns a copy of the graph name.
AllocatedStringPtr GetDomainAllocated (OrtAllocator *allocator) const
Returns a copy of the domain name.
AllocatedStringPtr GetDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the description.
AllocatedStringPtr GetGraphDescriptionAllocated (OrtAllocator *allocator) const
Returns a copy of the graph description.
std::vector< AllocatedStringPtr > GetCustomMetadataMapKeysAllocated (OrtAllocator *allocator) const
Returns a vector of copies of the custom metadata keys.
AllocatedStringPtr LookupCustomMetadataMapAllocated (const char *key, OrtAllocator *allocator) const
Looks up a value by a key in the Custom Metadata map.
int64_t GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
Public Member Functions inherited from Ort::detail::Base< OrtModelMetadata >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
Base (const Base &)=delete
Base (Base &&v) noexcept
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
~Base ()
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
Base & operator= (const Base &)=delete
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Public Types inherited from Ort::detail::Base< OrtModelMetadata >
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
using contained_type = OrtModelMetadata
Protected Attributes inherited from Ort::detail::Base< OrtModelMetadata >
contained_type * p_
Detailed Description
Wrapper around ::OrtModelMetadata.
Constructor & Destructor Documentation
ModelMetadata() [1/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [2/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [3/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [4/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [5/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [6/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [7/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [8/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [9/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [10/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [11/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [12/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
ModelMetadata() [13/14]
Ort::ModelMetadata::ModelMetadata (std::nullptr_t) explicit
Create an empty ModelMetadata object, must be assigned a valid one to be used.
ModelMetadata() [14/14]
Ort::ModelMetadata::ModelMetadata (OrtModelMetadata * p) explicit
Used for interop with the C API.
Member Function Documentation
GetCustomMetadataMapKeysAllocated() [1/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
GetCustomMetadataMapKeysAllocated() [2/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetCustomMetadataMapKeysAllocated() [3/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetCustomMetadataMapKeysAllocated() [4/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetCustomMetadataMapKeysAllocated() [5/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetCustomMetadataMapKeysAllocated() [6/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetCustomMetadataMapKeysAllocated() [7/7]
std::vector< AllocatedStringPtr > Ort::ModelMetadata::GetCustomMetadataMapKeysAllocated (OrtAllocator * allocator) const
Returns a vector of copies of the custom metadata keys.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance std::vector of smart pointers that would deallocate the buffers when out of scope. The OrtAllocator instance must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetCustomMetadataMapKeys
GetDescriptionAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDescriptionAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::GetDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDescription
GetDomainAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetDomainAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::GetDomainAllocated (OrtAllocator * allocator) const
Returns a copy of the domain name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetDomain
GetGraphDescriptionAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
GetGraphDescriptionAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphDescriptionAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphDescriptionAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphDescriptionAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphDescriptionAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphDescriptionAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphDescriptionAllocated (OrtAllocator * allocator) const
Returns a copy of the graph description.
Parameters
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphDescription
GetGraphNameAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
GetGraphNameAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetGraphNameAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetGraphNameAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetGraphNameAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetGraphNameAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetGraphNameAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::GetGraphNameAllocated (OrtAllocator * allocator) const
Returns a copy of the graph name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetGraphName
GetProducerNameAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
GetProducerNameAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetProducerNameAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetProducerNameAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetProducerNameAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetProducerNameAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetProducerNameAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::GetProducerNameAllocated (OrtAllocator * allocator) const
Returns a copy of the producer name.
Parameters
allocator to allocate memory for the copy of the name returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataGetProducerName
GetVersion() [1/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
GetVersion() [2/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
GetVersion() [3/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
GetVersion() [4/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
GetVersion() [5/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
GetVersion() [6/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
GetVersion() [7/7]
int64_t Ort::ModelMetadata::GetVersion () const
Wraps OrtApi::ModelMetadataGetVersion.
LookupCustomMetadataMapAllocated() [1/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
References Ort::GetApi(), Ort::detail::Base< OrtModelMetadata >::p_, and Ort::ThrowOnError().
LookupCustomMetadataMapAllocated() [2/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
LookupCustomMetadataMapAllocated() [3/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
LookupCustomMetadataMapAllocated() [4/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
LookupCustomMetadataMapAllocated() [5/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
LookupCustomMetadataMapAllocated() [6/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
LookupCustomMetadataMapAllocated() [7/7]
AllocatedStringPtr Ort::ModelMetadata::LookupCustomMetadataMapAllocated (const char * key, OrtAllocator * allocator) const
Looks up a value by a key in the Custom Metadata map.
Parameters
key zero terminated string key to lookup
allocator to allocate memory for the copy of the string returned
Returns
a instance of smart pointer that would deallocate the buffer when out of scope. maybe nullptr if key is not found.
The OrtAllocator instances must be valid at the point of memory release. Wraps OrtApi::ModelMetadataLookupCustomMetadataMap
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h