CI-FirstResponders: Ort::detail::TensorTypeAndShapeInfoImpl< T > Struct Template Reference
Ort::detail::TensorTypeAndShapeInfoImpl< T > Struct Template Reference
#include <onnxruntime_cxx_api.h>
Public Types
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
using B = Base< T >
Public Types inherited from Ort::detail::Base< T >
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
using contained_type = T
Public Member Functions
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
ONNXTensorElementDataType GetElementType () const
Wraps OrtApi::GetTensorElementType.
size_t GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
size_t GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
void GetDimensions (int64_t *values, size_t values_count) const
Wraps OrtApi::GetDimensions.
void GetSymbolicDimensions (const char **values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
std::vector< int64_t > GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
Public Member Functions inherited from Ort::detail::Base< T >
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
constexpr Base ()=default
constexpr Base (contained_type *p) noexcept
~Base ()
Base (const Base &)=delete
Base & operator= (const Base &)=delete
Base (Base &&v) noexcept
Base & operator= (Base &&v) noexcept
constexpr operator contained_type * () const noexcept
contained_type * release ()
Relinquishes ownership of the contained C object pointer The underlying object is not destroyed.
Additional Inherited Members
Protected Attributes inherited from Ort::detail::Base< T >
contained_type * p_ {}
Member Typedef Documentation
B [1/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [2/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [3/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [4/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [5/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [6/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
B [7/7]
template<typename T > using Ort::detail::TensorTypeAndShapeInfoImpl< T >::B = Base<T>
Member Function Documentation
GetDimensions() [1/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
References Ort::GetApi(), and Ort::ThrowOnError().
GetDimensions() [2/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensions() [3/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensions() [4/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensions() [5/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensions() [6/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensions() [7/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensions (int64_t * values, size_t values_count) const
Wraps OrtApi::GetDimensions.
Deprecated:
use GetShape() returning std::vector [[deprecated]] This interface is unsafe to use
GetDimensionsCount() [1/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount
Wraps OrtApi::GetDimensionsCount.
References Ort::GetApi(), and Ort::ThrowOnError().
GetDimensionsCount() [2/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetDimensionsCount() [3/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetDimensionsCount() [4/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetDimensionsCount() [5/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetDimensionsCount() [6/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetDimensionsCount() [7/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetDimensionsCount () const
Wraps OrtApi::GetDimensionsCount.
GetElementCount() [1/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount
Wraps OrtApi::GetTensorShapeElementCount.
References Ort::GetApi(), and Ort::ThrowOnError().
GetElementCount() [2/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementCount() [3/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementCount() [4/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementCount() [5/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementCount() [6/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementCount() [7/7]
template<typename T > size_t Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementCount () const
Wraps OrtApi::GetTensorShapeElementCount.
GetElementType() [1/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType
Wraps OrtApi::GetTensorElementType.
References Ort::GetApi(), and Ort::ThrowOnError().
GetElementType() [2/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetElementType() [3/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetElementType() [4/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetElementType() [5/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetElementType() [6/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetElementType() [7/7]
template<typename T > ONNXTensorElementDataType Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetElementType () const
Wraps OrtApi::GetTensorElementType.
GetShape() [1/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
References Ort::GetApi(), and Ort::ThrowOnError().
GetShape() [2/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetShape() [3/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetShape() [4/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetShape() [5/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetShape() [6/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetShape() [7/7]
template<typename T > std::vector< int64_t > Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetShape () const
Uses GetDimensionsCount & GetDimensions to return a std::vector of the shape.
GetSymbolicDimensions() [1/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
References Ort::GetApi(), and Ort::ThrowOnError().
GetSymbolicDimensions() [2/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
GetSymbolicDimensions() [3/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
GetSymbolicDimensions() [4/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
GetSymbolicDimensions() [5/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
GetSymbolicDimensions() [6/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
GetSymbolicDimensions() [7/7]
template<typename T > void Ort::detail::TensorTypeAndShapeInfoImpl< T >::GetSymbolicDimensions (const char ** values, size_t values_count) const
Wraps OrtApi::GetSymbolicDimensions.
The documentation for this struct was generated from the following files:
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_api.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
//?/D:/bak/GithubRepos/CI-FirstResponders/DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool.Tests.xUnit/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
DispatchersMonitoringTool/DispatchersMonitoringTool/bin/Debug/net6.0-windows10.0.19041.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MobileVitalsMonitoringTool/MobileVitalsMonitoringTool/MobileVitalsMonitoringTool.Android/obj/Debug/130/lp/105/jl/headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h
MonitoringSuiteLibrary/UnitTests/bin/Debug/net6.0/runtimes/ios/native/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/Headers/onnxruntime_cxx_inline.h